//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "SXVideoViewControllerConfiguration.h"

@class NUVideoViewControllerAdConfiguration;

@interface NUVideoViewControllerConfiguration : NSObject <NSCopying, SXVideoViewControllerConfiguration>
{
    _Bool _preferredMuteState;
    _Bool _pagingAllowed;
    _Bool _sharingEnabled;
    NUVideoViewControllerAdConfiguration *_adConfiguration;
}

@property(readonly, copy, nonatomic) NUVideoViewControllerAdConfiguration *adConfiguration; // @synthesize adConfiguration=_adConfiguration;
@property(readonly, nonatomic, getter=isSharingEnabled) _Bool sharingEnabled; // @synthesize sharingEnabled=_sharingEnabled;
@property(readonly, nonatomic, getter=isPagingAllowed) _Bool pagingAllowed; // @synthesize pagingAllowed=_pagingAllowed;
@property(readonly, nonatomic) _Bool preferredMuteState; // @synthesize preferredMuteState=_preferredMuteState;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSharingEnabled:(_Bool)arg1 preferredMuteState:(_Bool)arg2 pagingAllowed:(_Bool)arg3 adConfiguration:(id)arg4;
- (id)init;

@end

