//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTitledPlatterView.h"

#import "NCNotificationStaticContentAccepting.h"

@class MTFontProvider, NCNotificationContentView, NCNotificationGrabberView, NSArray, NSDate, NSString, NSTimeZone, UIImage, UIView;

@interface NCNotificationShortLookView : MTTitledPlatterView <NCNotificationStaticContentAccepting>
{
    MTFontProvider *_fontProvider;
    NCNotificationContentView *_notificationContentView;
    NCNotificationGrabberView *_grabberView;
}

- (void).cxx_destruct;
- (_Bool)adjustForContentSizeCategoryChange;
- (void)setAdjustsFontForContentSizeCategory:(_Bool)arg1;
- (_Bool)adjustsFontForContentSizeCategory;
- (_Bool)_shouldShowGrabber;
- (void)_layoutGrabber;
- (id)_grabberView;
- (void)layoutSubviews;
- (void)_configureNotificationContentViewIfNecessary;
- (id)_newNotificationContentView;
- (void)_configureHeaderContentView;
- (void)setBackgroundView:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)contentSizeForSize:(struct CGSize)arg1;
- (struct CGSize)sizeThatFitsContentWithSize:(struct CGSize)arg1;
- (id)_notificationContentView;
- (void)_setFontProvider:(id)arg1;
- (id)_fontProvider;
@property(nonatomic) unsigned long long messageNumberOfLines;
@property(retain, nonatomic) UIView *accessoryView;
@property(retain, nonatomic) UIImage *thumbnail;
@property(copy, nonatomic) NSString *secondaryText;
@property(copy, nonatomic) NSString *primarySubtitleText;
@property(copy, nonatomic) NSString *primaryText;
@property(retain, nonatomic) NSArray *interfaceActions;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(copy, nonatomic) NSDate *date;
@property(readonly, nonatomic, getter=isDateAllDay) _Bool dateAllDay;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) UIImage *icon;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSTimeZone *timeZone;
@property(copy, nonatomic) NSString *title;

@end

