//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVMLKit/TVContainerCollectionViewCell.h>

#import <VideosUI/TVAuxiliaryViewSelecting-Protocol.h>

@class IKViewElement, NSArray, NSString, UIView, VUIEditorialCellLayout, _TVStackingPosterView;
@protocol TVAuxiliaryViewSelecting;

__attribute__((visibility("hidden")))
@interface VUIEditorialCollectionViewCell : TVContainerCollectionViewCell <TVAuxiliaryViewSelecting>
{
    UIView<TVAuxiliaryViewSelecting> *_selectingView;
    IKViewElement *_viewElement;
    NSArray *_labelViews;
    _TVStackingPosterView *_stackingPosterView;
    UIView *_stackView;
    VUIEditorialCellLayout *_layout;
}

+ (id)configureViewWithElement:(id)arg1 existingCell:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) VUIEditorialCellLayout *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) UIView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) _TVStackingPosterView *stackingPosterView; // @synthesize stackingPosterView=_stackingPosterView;
@property(copy, nonatomic) NSArray *labelViews; // @synthesize labelViews=_labelViews;
@property(retain, nonatomic) IKViewElement *viewElement; // @synthesize viewElement=_viewElement;
@property(retain, nonatomic) UIView<TVAuxiliaryViewSelecting> *selectingView; // @synthesize selectingView=_selectingView;
- (struct UIEdgeInsets)selectionMarginsForSize:(struct CGSize)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (struct CGSize)_layoutWithSize:(struct CGSize)arg1 metricsOnly:(_Bool)arg2;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

