//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <VideosUI/NSObject-Protocol.h>

@class UIImage;
@protocol VUIOverlayLayoutProtocol;

@protocol VUIOverlayViewProtocol <NSObject>
@property(readonly, nonatomic) id <VUIOverlayLayoutProtocol> overlayLayout;
@property(retain, nonatomic) UIImage *backgroundImageForMaterialRendering;
- (void)backgroundImageSizeDidChange:(struct CGSize)arg1;
- (void)reset;
@end

