//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MCDPlayModeButton, MCDRepeatButton, NSArray, UIStackView;

@interface MCDPlayModeControlView : UIView
{
    _Bool _fuseSubscriberLayout;
    _Bool _showsArtwork;
    MCDRepeatButton *_repeatButton;
    MCDPlayModeButton *_moreButton;
    MCDPlayModeButton *_shuffleButton;
    MCDPlayModeButton *_addToLibraryButton;
    MCDPlayModeButton *_playbackRateButton;
    UIStackView *_stackView;
    NSArray *_activeButtonLayoutConstraints;
}

@property(retain, nonatomic) NSArray *activeButtonLayoutConstraints; // @synthesize activeButtonLayoutConstraints=_activeButtonLayoutConstraints;
@property(nonatomic) _Bool showsArtwork; // @synthesize showsArtwork=_showsArtwork;
@property(readonly, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) _Bool fuseSubscriberLayout; // @synthesize fuseSubscriberLayout=_fuseSubscriberLayout;
@property(readonly, nonatomic) MCDPlayModeButton *playbackRateButton; // @synthesize playbackRateButton=_playbackRateButton;
@property(readonly, nonatomic) MCDPlayModeButton *addToLibraryButton; // @synthesize addToLibraryButton=_addToLibraryButton;
@property(readonly, nonatomic) MCDPlayModeButton *shuffleButton; // @synthesize shuffleButton=_shuffleButton;
@property(readonly, nonatomic) MCDPlayModeButton *moreButton; // @synthesize moreButton=_moreButton;
@property(readonly, nonatomic) MCDRepeatButton *repeatButton; // @synthesize repeatButton=_repeatButton;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)_updateButtonLayouts;
@property(readonly, nonatomic) double maximumButtonWidth;
- (id)_visibleControlButtons;
- (id)initWithFrame:(struct CGRect)arg1;

@end

