//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeUI/HUQuickControlControllableView-Protocol.h>

@class UIGestureRecognizer;
@protocol HUQuickControlViewInteractionDelegate;

@protocol HUQuickControlInteractiveView <HUQuickControlControllableView>
@property(readonly, nonatomic, getter=isUserInteractionActive) _Bool userInteractionActive;
@property(nonatomic) __weak id <HUQuickControlViewInteractionDelegate> interactionDelegate;
- (void)beginUserInteractionWithFirstTouchGestureRecognizer:(UIGestureRecognizer *)arg1;
@end

