//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class HUSignificantEventOffsetPickerCell, NSDateComponents;

@protocol HUSignificantEventOffsetPickerDelegate <NSObject>

@optional
- (void)significantEventOffsetPicker:(HUSignificantEventOffsetPickerCell *)arg1 didSelectOffset:(NSDateComponents *)arg2;
@end

