//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RelevanceEngine/REScriptASTNode.h>

@class REScriptToken;

@interface REScriptASTDeclarationNode : REScriptASTNode
{
    REScriptToken *_type;
    REScriptToken *_name;
    REScriptASTNode *_value;
}

+ (id)parseBuffer:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) REScriptASTNode *value; // @synthesize value=_value;
@property(readonly, nonatomic) REScriptToken *name; // @synthesize name=_name;
@property(readonly, nonatomic) REScriptToken *type; // @synthesize type=_type;
- (id)dependencies;
- (id)initWithName:(id)arg1 type:(id)arg2 expression:(id)arg3;

@end

