//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSListController.h"

@class HKHealthStore, UIProgressHUD;

@interface HKHealthManageStorageViewController : PSListController
{
    long long _status;
    UIProgressHUD *_spinnerView;
    HKHealthStore *_healthStore;
}

@property(readonly, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
- (void).cxx_destruct;
- (void)_disableAndDelete:(id)arg1;
- (void)confirmDisable:(id)arg1;
- (void)hideSpinner;
- (void)showSpinnerMessage:(id)arg1;
- (void)_loadCloudSyncStorageStatus;
- (id)specifiers;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

@end

