//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthUI/HKAxisLabelDimension-Protocol.h>

@protocol HKHistogramAxisDimensionDataSource;

@interface HKHistogramAxisDimension : NSObject <HKAxisLabelDimension>
{
    id <HKHistogramAxisDimensionDataSource> _dataSource;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <HKHistogramAxisDimensionDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)stringForLocation:(id)arg1;
- (void)setStepSizeForLabels:(double)arg1;
- (double)ticksPerStepSize:(double)arg1;
- (double)niceStepSizeLargerThan:(double)arg1;

@end

