//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, TSCECalculationEngine, TSTTableInfo;

@interface TSTHiddenStatesOwner : NSObject
{
    TSTTableInfo *_tableInfo;
    TSCECalculationEngine *_calcEngine;
    UUIDData_5fbc143e _baseTableUID;
    UUIDData_5fbc143e _ownerUID;
    NSMutableDictionary *_hiddenStatesByUuid;
    NSMutableDictionary *_hiddenStatesByExtentUuid;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) UUIDData_5fbc143e ownerUID; // @synthesize ownerUID=_ownerUID;
@property(nonatomic) UUIDData_5fbc143e baseTableUID; // @synthesize baseTableUID=_baseTableUID;
- (void)remapTableUIDsInFormulasWithMap:(const UUIDMap_71b9b5e2 *)arg1 calcEngine:(id)arg2;
-     // Error parsing type: v32@0:8^{HiddenStatesOwnerArchive=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}{RepeatedPtrField<TST::HiddenStatesArchive>=^{Arena}ii^{Rep}}^{UUID}}16@24, name: saveToArchive:archiver:
-     // Error parsing type: @40@0:8r^{HiddenStatesOwnerArchive=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}{RepeatedPtrField<TST::HiddenStatesArchive>=^{Arena}ii^{Rep}}^{UUID}}16@24r^{UUIDData<TSP::UUIDData>=(?=[16C]{?=CCCCCCCCCCCCCCCC}{?=QQ})}32, name: initWithArchive:unarchiver:forBaseTableUID:
- (void)didChangeExtentUids:(id)arg1;
- (void)willChangeExtentUids:(id)arg1;
- (void)unregisterHiddenStates:(id)arg1;
- (id)hiddenStatesByExtentUid:(const UUIDData_5fbc143e *)arg1;
- (id)hiddenStatesByUid:(const UUIDData_5fbc143e *)arg1;
- (void)registerHiddenStates:(id)arg1 baseOwnerUID:(const UUIDData_5fbc143e *)arg2;
- (id)calcEngine;
- (void)unregisterFromCalcEngine;
- (int)registerWithCalcEngine:(id)arg1 baseOwnerUID:(const UUIDData_5fbc143e *)arg2;
@property(nonatomic) __weak TSTTableInfo *tableInfo; // @synthesize tableInfo=_tableInfo;
- (id)tableModel;
- (id)description;
- (id)initWithBaseTableUID:(const UUIDData_5fbc143e *)arg1;
- (id)initWithBaseTableUID:(const UUIDData_5fbc143e *)arg1 ownerUID:(const UUIDData_5fbc143e *)arg2;

@end

