//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PencilKit/_PKInkColorButton.h>

@class CAShapeLayer;

@interface _PKFlatInkColorButton : _PKInkColorButton
{
    CAShapeLayer *_fillShapeLayer;
    CAShapeLayer *_strokeShapeLayer;
}

@property(retain, nonatomic) CAShapeLayer *strokeShapeLayer; // @synthesize strokeShapeLayer=_strokeShapeLayer;
@property(retain, nonatomic) CAShapeLayer *fillShapeLayer; // @synthesize fillShapeLayer=_fillShapeLayer;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithColor:(id)arg1 isCompact:(_Bool)arg2;

@end

