//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Notes/ICNFIMAPAggregateClientOperation.h>

@interface ICNFIMAPAggregateFetchUIDOperation : ICNFIMAPAggregateClientOperation
{
    unsigned int _expectedSize;
}

@property unsigned int expectedSize; // @synthesize expectedSize=_expectedSize;
- (long long)maxAllowedConnectionState;
- (long long)minRequiredConnectionState;
- (void)cleanupAfterCompletion;
- (id)activityString;
- (id)commandTypeString;
- (id)initWithOperations:(id)arg1;
- (id)initWithOperations:(id)arg1 expectedSize:(unsigned int)arg2;

@end

