//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DNDSRemoteServiceProviderAssertionDelegate.h"
#import "DNDSRemoteServiceProviderBehaviorResolutionDelegate.h"
#import "DNDSRemoteServiceProviderSettingsDelegate.h"
#import "DNDSRemoteServiceProviderStateDelegate.h"

@protocol DNDSRemoteServiceProviderDelegate <DNDSRemoteServiceProviderBehaviorResolutionDelegate, DNDSRemoteServiceProviderAssertionDelegate, DNDSRemoteServiceProviderStateDelegate, DNDSRemoteServiceProviderSettingsDelegate>
@end

