//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOLatLng, GEOMapRegion, NSMutableArray, NSString, PBDataReader;

@interface GEORPCorrectedLabel : PBCodable <NSCopying>
{
    PBDataReader *_reader;
    GEOLatLng *_coordinate;
    NSString *_correctedValue;
    NSMutableArray *_featureHandles;
    GEOMapRegion *_featureRegion;
    NSString *_originalValue;
    unsigned long long _uid;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    struct os_unfair_lock_s _readerLock;
    _Bool _localizedLabels;
    struct {
        unsigned int has_uid:1;
        unsigned int has_localizedLabels:1;
        unsigned int read_coordinate:1;
        unsigned int read_correctedValue:1;
        unsigned int read_featureHandles:1;
        unsigned int read_featureRegion:1;
        unsigned int read_originalValue:1;
        unsigned int wrote_coordinate:1;
        unsigned int wrote_correctedValue:1;
        unsigned int wrote_featureHandles:1;
        unsigned int wrote_featureRegion:1;
        unsigned int wrote_originalValue:1;
        unsigned int wrote_uid:1;
        unsigned int wrote_localizedLabels:1;
    } _flags;
}

+ (_Bool)isValid:(id)arg1;
+ (Class)featureHandleType;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (void)readAll:(_Bool)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasLocalizedLabels;
@property(nonatomic) _Bool localizedLabels;
@property(nonatomic) _Bool hasUid;
@property(nonatomic) unsigned long long uid;
@property(retain, nonatomic) GEOLatLng *coordinate;
@property(readonly, nonatomic) _Bool hasCoordinate;
- (void)_readCoordinate;
- (id)featureHandleAtIndex:(unsigned long long)arg1;
- (unsigned long long)featureHandlesCount;
- (void)_addNoFlagsFeatureHandle:(id)arg1;
- (void)addFeatureHandle:(id)arg1;
- (void)clearFeatureHandles;
@property(retain, nonatomic) NSMutableArray *featureHandles;
- (void)_readFeatureHandles;
@property(retain, nonatomic) GEOMapRegion *featureRegion;
@property(readonly, nonatomic) _Bool hasFeatureRegion;
- (void)_readFeatureRegion;
@property(retain, nonatomic) NSString *correctedValue;
@property(readonly, nonatomic) _Bool hasCorrectedValue;
- (void)_readCorrectedValue;
@property(retain, nonatomic) NSString *originalValue;
@property(readonly, nonatomic) _Bool hasOriginalValue;
- (void)_readOriginalValue;
- (id)initWithData:(id)arg1;
- (id)init;

@end

