//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GEOActiveTileGroupMigrator.h"

@class GEOResourceManifestConfiguration, NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface GEOSearchAttributionManifestVersionMigrator : NSObject <GEOActiveTileGroupMigrator>
{
    GEOResourceManifestConfiguration *_manifestConfiguration;
    NSObject<OS_dispatch_queue> *_isolationQueue;
    NSMutableArray *_runningTasks;
}

- (void).cxx_destruct;
- (void)_removeRunningTask:(id)arg1;
- (void)_addRunningTask:(id)arg1;
- (id)taskForNewTileGroup:(id)arg1 inResourceManifest:(id)arg2 oldTileGroup:(id)arg3 activeScales:(id)arg4 activeScenarios:(id)arg5 updateType:(long long)arg6;
- (id)initWithManifestConfiguration:(id)arg1 mapLayerDataManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

