//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <QuickLook/QLDetailItemViewController.h>

@class QLDetailItemViewControllerState;

__attribute__((visibility("hidden")))
@interface QLZipItemViewController : QLDetailItemViewController
{
    unsigned long long _numberOfContainedFiles;
    QLDetailItemViewControllerState *_readyToUnzipState;
    QLDetailItemViewControllerState *_unzippingState;
    QLDetailItemViewControllerState *_unableToUnzipState;
}

+ (_Bool)shouldBeRemoteForContentType:(id)arg1;
+ (id)supportedContentTypes;
+ (Class)transformerClass;
- (void).cxx_destruct;
- (void)performAction;
- (void)setAppearance:(id)arg1 animated:(_Bool)arg2;
- (void)loadPreviewControllerWithContents:(id)arg1 context:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_updateZipInformationWithZipSize:(id)arg1;
- (void)viewDidLoad;

@end

