//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HDLiveDataCollector.h"

@class CMOdometer, HDLiveDataCollectorBuffer;

@interface NLOdometerDataCollector : HDLiveDataCollector
{
    CMOdometer *_odometer;
    HDLiveDataCollectorBuffer *_currentSensorDatumBuffer;
}

+ (int)odometerActivity;
+ (Class)sensorDatumClass;
+ (id)createCollectorsForCurrentHardware:(id)arg1;
- (void).cxx_destruct;
- (id)newSensorDatumBuffer;
- (void)stopPerformingUpdatesWithErrorEncountered:(_Bool)arg1;
- (id)hkObjectsFromSensorDatum:(id)arg1 context:(id)arg2;
- (void)beginUpdatesWithHandler:(CDUnknownBlockType)arg1;

@end

