//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HDAggregateDataCollector.h"

@class CMSwimTracker;

@interface NLSwimmingDataCollector : HDAggregateDataCollector
{
    CMSwimTracker *_swimTracker;
}

+ (Class)sensorDatumClass;
+ (id)createCollectorsForCurrentHardware:(id)arg1;
- (void).cxx_destruct;
- (id)quantitySampleFromSwimData:(id)arg1 toSwimData:(id)arg2 startDate:(id)arg3 endDate:(id)arg4;
- (_Bool)requiresSampleAggregation;
- (id)hkObjectsFromSensorData:(id)arg1 baseSensorDatum:(id)arg2 startDate:(id)arg3 endDate:(id)arg4;
- (void)fetchHistoricalSensorDataSinceDatum:(id)arg1 databaseIdentifier:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)beginUpdatesFromDatum:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)stopPerformingUpdatesWithErrorEncountered:(_Bool)arg1;
- (id)initWithProfile:(id)arg1;

@end

