//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CAMTimelapseState, NSArray, NSString;

@interface CAMTimelapseBackendSessionContext : NSObject
{
    NSString *_timelapseUUID;
    CAMTimelapseState *_state;
    NSArray *_filesToDelete;
    NSArray *_filesToWrite;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *filesToWrite; // @synthesize filesToWrite=_filesToWrite;
@property(retain, nonatomic) NSArray *filesToDelete; // @synthesize filesToDelete=_filesToDelete;
@property(retain, nonatomic) CAMTimelapseState *state; // @synthesize state=_state;
@property(readonly, nonatomic) NSString *timelapseUUID; // @synthesize timelapseUUID=_timelapseUUID;
- (id)description;
- (id)init;
- (id)initWithTimelapseUUID:(id)arg1;

@end

