//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol HDHealthRecordsAccountEventObserver, HDHealthRecordsSupportedChangeObserver;

@protocol HDHealthRecordsProfileExtension
- (void)removeAccountEventObserver:(id <HDHealthRecordsAccountEventObserver>)arg1;
- (void)addAccountEventObserver:(id <HDHealthRecordsAccountEventObserver>)arg1;
- (_Bool)hasAccounts:(_Bool *)arg1 error:(id *)arg2;
- (void)unregisterHealthRecordsSupportedChangeObserver:(id <HDHealthRecordsSupportedChangeObserver>)arg1;
- (void)registerHealthRecordsSupportedChangeObserver:(id <HDHealthRecordsSupportedChangeObserver>)arg1;
- (_Bool)deviceConfigurationSupportsHealthRecords:(_Bool *)arg1 error:(id *)arg2;
@end

