//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PXProtoFeature.h"

@class NSArray, NSString, UIColor;

@interface PXMemoriesDebugFeature : NSObject <PXProtoFeature>
{
    NSString *_featureLocalizedTitle;
    UIColor *_featureTintColor;
    unsigned long long _type;
    NSString *_localizedTitle;
}

+ (id)_tintColorForFeatureType:(unsigned long long)arg1;
@property(readonly, nonatomic) NSString *localizedTitle; // @synthesize localizedTitle=_localizedTitle;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *featureLocalizedTitle; // @synthesize featureLocalizedTitle=_featureLocalizedTitle;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *localizedTypeStringValue;
@property(readonly, nonatomic) UIColor *featureTintColor; // @synthesize featureTintColor=_featureTintColor;
@property(readonly, nonatomic) long long featureGroupIndex;
@property(readonly, nonatomic) long long featureKind;
- (id)initWithLocalizedTitle:(id)arg1 type:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSArray *featurePeople;
@property(readonly, nonatomic) double featureScore;
@property(readonly, nonatomic) UIColor *featureSelectedTintColor;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

