//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/PXSettings.h>

@interface PXPeopleUISettings : PXSettings
{
    _Bool _alwaysShowBootstrap;
    _Bool _alwaysShowCandidateWidget;
    _Bool _alwaysShowMe;
    _Bool _displayBootstrapSuggestionType;
    _Bool _displayConfirmAdditionalSuggestionType;
    _Bool _displayConfirmationPhotoDate;
    _Bool _debugBlurredCells;
    _Bool _showContactSuggestions;
    _Bool _showMaybeContact;
}

+ (id)sharedInstance;
+ (id)settingsControllerModule;
@property(nonatomic, getter=shouldShowMaybeContact) _Bool showMaybeContact; // @synthesize showMaybeContact=_showMaybeContact;
@property(nonatomic, getter=shouldShowContactSuggestions) _Bool showContactSuggestions; // @synthesize showContactSuggestions=_showContactSuggestions;
@property(nonatomic, getter=shouldDebugBlurredCells) _Bool debugBlurredCells; // @synthesize debugBlurredCells=_debugBlurredCells;
@property(nonatomic, getter=shouldDisplayConfirmationPhotoDate) _Bool displayConfirmationPhotoDate; // @synthesize displayConfirmationPhotoDate=_displayConfirmationPhotoDate;
@property(nonatomic, getter=shouldDisplayConfirmAdditionalSuggestionType) _Bool displayConfirmAdditionalSuggestionType; // @synthesize displayConfirmAdditionalSuggestionType=_displayConfirmAdditionalSuggestionType;
@property(nonatomic, getter=shouldDisplayBootstrapSuggestionType) _Bool displayBootstrapSuggestionType; // @synthesize displayBootstrapSuggestionType=_displayBootstrapSuggestionType;
@property(nonatomic, getter=shouldAlwaysShowMe) _Bool alwaysShowMe; // @synthesize alwaysShowMe=_alwaysShowMe;
@property(nonatomic, getter=shouldAlwaysShowCandidateWidget) _Bool alwaysShowCandidateWidget; // @synthesize alwaysShowCandidateWidget=_alwaysShowCandidateWidget;
@property(nonatomic, getter=shouldAlwaysShowBootstrap) _Bool alwaysShowBootstrap; // @synthesize alwaysShowBootstrap=_alwaysShowBootstrap;
- (void)setDefaultValues;
- (id)parentSettings;

@end

