//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface IMKLayoutLine : NSObject
{
    NSString *_groupName;
    NSMutableArray *_layoutUnitsInternal;
}

@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(retain, nonatomic) NSMutableArray *layoutUnitsInternal; // @synthesize layoutUnitsInternal=_layoutUnitsInternal;
@property(readonly, nonatomic) NSArray *layoutUnits;
- (void)addLayoutUnit:(id)arg1;
- (void)dealloc;

@end

