//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DOCAppearanceProtocol.h"
#import "DOCHostSourceViewControllerProxy.h"
#import "UIPopoverPresentationControllerDelegate.h"

@class DOCAppearance, DOCConfiguration, NSArray, NSString, UINavigationController, UIViewController<DOCRemoteAppearanceInterface>, _UIResilientRemoteViewContainerViewController;

@interface DOCSourceViewController : UIViewController <DOCHostSourceViewControllerProxy, DOCAppearanceProtocol, UIPopoverPresentationControllerDelegate>
{
    _UIResilientRemoteViewContainerViewController *_remoteViewController;
    UIViewController<DOCRemoteAppearanceInterface> *_localViewController;
    DOCAppearance *_lastAppearance;
    _Bool _inPopoverMode;
    _Bool _editing;
    UINavigationController *_internalNavigationController;
    UIViewController *_currentParent;
    id <DOCSourceViewControllerDelegate> _sourceDelegate;
    NSArray *_additionalTrailingNavigationBarButtonItems;
    id <DOCServiceSourceViewControllerProxy> _serviceProxy;
    DOCConfiguration *_configuration;
}

@property(readonly) DOCConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly) id <DOCServiceSourceViewControllerProxy> serviceProxy; // @synthesize serviceProxy=_serviceProxy;
@property(retain, nonatomic) NSArray *additionalTrailingNavigationBarButtonItems; // @synthesize additionalTrailingNavigationBarButtonItems=_additionalTrailingNavigationBarButtonItems;
@property(nonatomic) __weak id <DOCSourceViewControllerDelegate> sourceDelegate; // @synthesize sourceDelegate=_sourceDelegate;
- (void).cxx_destruct;
- (void)updateAppearance:(id)arg1;
- (void)_updateDefaultPreferredContentSizeWithSize:(struct CGSize)arg1;
- (struct CGSize)_defaultPreferredContentSize;
- (void)_updateAppearance;
- (void)updatePreferredSize:(struct CGSize)arg1;
- (void)didSelectLocation:(id)arg1;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (void)prepareForPopoverPresentation:(id)arg1;
- (void)updateViewsForParent:(id)arg1;
- (void)embedViewController:(id)arg1;
- (void)didPickItem:(id)arg1;
- (void)showLocation:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)currentlySelectedLocationDidChange:(id)arg1;
- (void)removeViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)_toggleEditMode;
- (_Bool)isEditing;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updateNavigationButtons;
- (void)_dismissViewController;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (id)remoteInterface;
- (id)remoteViewController;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithConfiguration:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

