//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface CNPostalAddressEditorNavigationController : UINavigationController
{
    id <CNPostalAddressEditorDelegate> _addressEditorDelegate;
}

@property(nonatomic) __weak id <CNPostalAddressEditorDelegate> addressEditorDelegate; // @synthesize addressEditorDelegate=_addressEditorDelegate;
- (void).cxx_destruct;
- (void)doneWithContact:(id)arg1 propertyKey:(id)arg2;
- (void)setTitle:(id)arg1;
- (id)initWithFirstName:(id)arg1 lastName:(id)arg2 addressDictionary:(id)arg3 label:(id)arg4;
- (id)initWithPropertyKey:(id)arg1 label:(id)arg2;
- (id)initWithContact:(id)arg1 propertyKey:(id)arg2 editNames:(_Bool)arg3;

@end

