//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface TVCKTertiaryView : UIView
{
    NSArray *_tertiaryViews;
    double _viewSpacing;
}

@property(nonatomic) double viewSpacing; // @synthesize viewSpacing=_viewSpacing;
@property(retain, nonatomic) NSArray *tertiaryViews; // @synthesize tertiaryViews=_tertiaryViews;
- (void).cxx_destruct;
@property(readonly, nonatomic) double labelHeight;
@property(readonly, nonatomic) double maximumLabelBasedY;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

