//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TVContentPartnerKitUI/NSXPCListenerDelegate-Protocol.h>
#import <TVContentPartnerKitUI/TVCKRemoteNotifierDelegate-Protocol.h>
#import <TVContentPartnerKitUI/TVCKStoreContentMetadataFetchOperationDelegate-Protocol.h>
#import <TVContentPartnerKitUI/TVCKStoreFavoritesFactoryDataSource-Protocol.h>
#import <TVContentPartnerKitUI/TVCKStoreFavoritesServerProtocol-Protocol.h>

@class NSMutableSet, NSNumber, NSOperationQueue, NSString, NSTimer, TVCKRemoteNotifier, TVCKStoreContentMetadataCache, TVCKStoreFavoritesFactory, TVCKSyncingKeyValueStore;

@interface TVCKStoreFavoritesService : NSObject <TVCKStoreContentMetadataFetchOperationDelegate, TVCKStoreFavoritesFactoryDataSource, TVCKRemoteNotifierDelegate, NSXPCListenerDelegate, TVCKStoreFavoritesServerProtocol>
{
    _Bool _shouldSynchronizeKeyValueStore;
    NSOperationQueue *_operationQueue;
    TVCKStoreContentMetadataCache *_metadataCache;
    TVCKStoreFavoritesFactory *_itemFactory;
    NSNumber *_highestUserOrder;
    NSMutableSet *_activeClients;
    TVCKSyncingKeyValueStore *_keyValueStore;
    unsigned long long _numberOfPendingSyncCalls;
    id _preferencesObserver;
    TVCKRemoteNotifier *_remoteNotifier;
    NSTimer *_pollingTimer;
}

+ (id)sharedService;
- (void).cxx_destruct;
@property(nonatomic) __weak NSTimer *pollingTimer; // @synthesize pollingTimer=_pollingTimer;
@property(nonatomic) _Bool shouldSynchronizeKeyValueStore; // @synthesize shouldSynchronizeKeyValueStore=_shouldSynchronizeKeyValueStore;
@property(retain, nonatomic) TVCKRemoteNotifier *remoteNotifier; // @synthesize remoteNotifier=_remoteNotifier;
@property(retain, nonatomic) id preferencesObserver; // @synthesize preferencesObserver=_preferencesObserver;
@property unsigned long long numberOfPendingSyncCalls; // @synthesize numberOfPendingSyncCalls=_numberOfPendingSyncCalls;
@property(retain, nonatomic) TVCKSyncingKeyValueStore *keyValueStore; // @synthesize keyValueStore=_keyValueStore;
@property(retain, nonatomic) NSMutableSet *activeClients; // @synthesize activeClients=_activeClients;
@property(retain, nonatomic) NSNumber *highestUserOrder; // @synthesize highestUserOrder=_highestUserOrder;
@property(retain, nonatomic) TVCKStoreFavoritesFactory *itemFactory; // @synthesize itemFactory=_itemFactory;
@property(retain, nonatomic) TVCKStoreContentMetadataCache *metadataCache; // @synthesize metadataCache=_metadataCache;
@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)endMonitoringForChanges;
- (void)beginMonitoringForChanges;
- (void)removeAllItemsInCategory:(unsigned long long)arg1;
- (void)removeItemWithAdamID:(id)arg1;
- (void)addItemWithAdamID:(id)arg1;
- (void)moveItemInCategory:(unsigned long long)arg1 fromIndex:(unsigned long long)arg2 toIndex:(unsigned long long)arg3;
- (void)fetchInfoForShowsWithAdamIDs:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)fetchItemsInCategory:(unsigned long long)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)fetchCountOfItemsInCategory:(unsigned long long)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)_fetchItemsInCategory:(unsigned long long)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (void)fetchLightWeightItemsInCategory:(unsigned long long)arg1 withReplyHandler:(CDUnknownBlockType)arg2;
- (_Bool)_doesItem:(id)arg1 belongToCategory:(unsigned long long)arg2;
- (void)fetchStatusOfItemsInContentCategory:(unsigned long long)arg1 withAdamIDs:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (void)fetchStatusOfItemInContentCategory:(unsigned long long)arg1 withAdamID:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (void)fetchLookupItemsForAdamIDs:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)storeContentMetadataFetchOperation:(id)arg1 obtainedLookupItems:(id)arg2 withExpirationDate:(id)arg3;
- (void)remoteNotifier:(id)arg1 didReceiveRemoteNotificationWithUserInfo:(id)arg2;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)removeClient:(id)arg1;
- (void)addClient:(id)arg1;
- (void)_removeClient:(id)arg1;
- (void)_addClient:(id)arg1;
- (void)_ensureAuthenticatedAccountExistsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_pollingTimerFired:(id)arg1;
- (_Bool)_items:(id)arg1 containsItemWithAdamID:(id)arg2;
- (void)_fetchLookupItemsForAdamIDs:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)_enqueueOperationWithBlock:(CDUnknownBlockType)arg1;
- (void)_updateItems:(id)arg1 sendingChangeNotification:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)_fetchRealAdamIDForAdamID:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)_fetchRealAdamIDsForAdamIDs:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)_updateLastKnownSortMode;
- (void)_updateLastKnownSortModeInCategory:(unsigned long long)arg1 sendingChangeNotification:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)_keyValueStoreVersionDidChange:(id)arg1;
- (void)_keyValueStoreDidReset:(id)arg1;
- (void)_sendNotificationToActiveClientsForAddingItem:(id)arg1;
- (void)_sendNotificationToActiveClientsForRemovingItems:(id)arg1;
- (void)_sendChangeNotificationToActiveClients;
- (void)_synchronizeKeyValueStoreWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_obtainKeyValueStoreWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_endIgnoringKeyValueStoreChanges;
- (void)_beginIgnoringKeyValueStoreChanges;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

