//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, SKUIEditorialLinkLayout, UIColor;
@protocol SKUIEditorialLinkViewDelegate;

__attribute__((visibility("hidden")))
@interface SKUIEditorialLinkView : UIView
{
    NSMutableArray *_buttons;
    id <SKUIEditorialLinkViewDelegate> _delegate;
    UIColor *_highlightedTextColor;
    long long _horizontalAlignment;
    SKUIEditorialLinkLayout *_layout;
    UIColor *_textColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SKUIEditorialLinkLayout *linkLayout; // @synthesize linkLayout=_layout;
@property(nonatomic) long long horizontalAlignment; // @synthesize horizontalAlignment=_horizontalAlignment;
@property(nonatomic) __weak id <SKUIEditorialLinkViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)_newButton;
- (void)_linkButtonAction:(id)arg1;
- (void)tintColorDidChange;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)layoutSubviews;
- (void)setColoringWithColorScheme:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

