//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IMDaemonCore/NSObject-Protocol.h>

@class IDSAccount, NSArray;

@protocol IDSAccountDelegate <NSObject>

@optional
- (void)account:(IDSAccount *)arg1 connectedDevicesChanged:(NSArray *)arg2;
- (void)account:(IDSAccount *)arg1 nearbyDevicesChanged:(NSArray *)arg2;
- (void)account:(IDSAccount *)arg1 devicesChanged:(NSArray *)arg2;
- (void)account:(IDSAccount *)arg1 isActiveChanged:(_Bool)arg2;
@end

