//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Metal/MTLPointerType.h>

@class MTLType;

__attribute__((visibility("hidden")))
@interface MTLPointerTypeInternal : MTLPointerType
{
    unsigned int _dataType;
    unsigned int _elementType;
    MTLType *_elementTypeInfo;
    unsigned int _access;
    unsigned int _alignment;
    unsigned int _dataSize;
    _Bool _elementIsArgumentBuffer;
    _Bool _isConstantBuffer;
}

- (unsigned int)dataSize;
- (unsigned int)alignment;
- (unsigned int)access;
- (unsigned int)elementType;
- (unsigned int)dataType;
- (id)formattedDescription:(unsigned int)arg1;
- (id)elementArrayType;
- (id)elementStructType;
- (_Bool)elementIsIndirectArgumentBuffer;
- (_Bool)elementIsArgumentBuffer;
- (_Bool)isConstantBuffer;
- (void)setAlignment:(unsigned int)arg1 dataSize:(unsigned int)arg2;
- (id)elementTypeDescription;
- (void)dealloc;
- (id)initWithElementType:(unsigned int)arg1 elementTypeDescription:(id)arg2 access:(unsigned int)arg3 alignment:(unsigned int)arg4 dataSize:(unsigned int)arg5 elementIsIndirectArgumentBuffer:(_Bool)arg6 isConstantBuffer:(_Bool)arg7;

@end

