//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MNCommuteDestination, MNCommuteDestinationUpdater;

@protocol MNCommuteDestinationUpdaterDelegate <NSObject>
@property(readonly, nonatomic) _Bool isMapsActive;
- (void)destinationUpdaterDidArrive:(MNCommuteDestinationUpdater *)arg1;
- (void)destinationUpdater:(MNCommuteDestinationUpdater *)arg1 didUpdateDestination:(MNCommuteDestination *)arg2;
@end

