//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVMLKit/JSExport-Protocol.h>

@class NSDictionary, NSString;

@protocol TVJSPrivacyController <JSExport>
@property(readonly, nonatomic) NSDictionary *PrivacyIdentifiers;
- (void)acknowledgePrivacyLink:(NSString *)arg1:(NSString *)arg2;
- (_Bool)shouldDisplayPrivacyLink:(NSString *)arg1;
@end

