//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <PencilKit/PKPaletteViewInternalDelegate-Protocol.h>
#import <PencilKit/UIGestureRecognizerDelegate-Protocol.h>

@class NSLayoutConstraint, NSString, PKPaletteView, UIPanGestureRecognizer, UITapGestureRecognizer, UIViewFloatAnimatableProperty;
@protocol PKPaletteHostViewDelegate;

@interface PKPaletteHostView : UIView <UIGestureRecognizerDelegate, PKPaletteViewInternalDelegate>
{
    _Bool _waitingForPaletteToMinimize;
    _Bool _waitingForPaletteToRotate;
    PKPaletteView *_paletteView;
    id <PKPaletteHostViewDelegate> _delegate;
    double _paletteViewCompactHeight;
    NSLayoutConstraint *_paletteWidthConstraint;
    NSLayoutConstraint *_paletteHeightConstraint;
    NSLayoutConstraint *_paletteTopConstraint;
    NSLayoutConstraint *_paletteBottomConstraint;
    NSLayoutConstraint *_paletteLeftConstraint;
    NSLayoutConstraint *_paletteRightConstraint;
    NSLayoutConstraint *_paletteCenterXConstraint;
    NSLayoutConstraint *_paletteCenterYConstraint;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapToExpandPaletteFromMinimizedGestureRecognizer;
    long long _dockingAppearance;
    long long _paletteDraggingBehavior;
    long long _paletteVisualState;
    long long _lastAnimatedPaletteVisualState;
    long long _lastNonMinimizedPaletteVisualState;
    unsigned long long _paletteCornerLocation;
    unsigned long long _paletteEdgeLocation;
    double _paletteSizeScaleFactor;
    UIViewFloatAnimatableProperty *_regularToMinimizedAnimatableProperty;
    UIViewFloatAnimatableProperty *_staticToRotatingAnimatableProperty;
    struct CGPoint _lastPaletteCenterInSelf;
}

@property(nonatomic) _Bool waitingForPaletteToRotate; // @synthesize waitingForPaletteToRotate=_waitingForPaletteToRotate;
@property(retain, nonatomic) UIViewFloatAnimatableProperty *staticToRotatingAnimatableProperty; // @synthesize staticToRotatingAnimatableProperty=_staticToRotatingAnimatableProperty;
@property(nonatomic) _Bool waitingForPaletteToMinimize; // @synthesize waitingForPaletteToMinimize=_waitingForPaletteToMinimize;
@property(retain, nonatomic) UIViewFloatAnimatableProperty *regularToMinimizedAnimatableProperty; // @synthesize regularToMinimizedAnimatableProperty=_regularToMinimizedAnimatableProperty;
@property(nonatomic) double paletteSizeScaleFactor; // @synthesize paletteSizeScaleFactor=_paletteSizeScaleFactor;
@property(nonatomic) unsigned long long paletteEdgeLocation; // @synthesize paletteEdgeLocation=_paletteEdgeLocation;
@property(nonatomic) unsigned long long paletteCornerLocation; // @synthesize paletteCornerLocation=_paletteCornerLocation;
@property(nonatomic) struct CGPoint lastPaletteCenterInSelf; // @synthesize lastPaletteCenterInSelf=_lastPaletteCenterInSelf;
@property(nonatomic) long long lastNonMinimizedPaletteVisualState; // @synthesize lastNonMinimizedPaletteVisualState=_lastNonMinimizedPaletteVisualState;
@property(nonatomic) long long lastAnimatedPaletteVisualState; // @synthesize lastAnimatedPaletteVisualState=_lastAnimatedPaletteVisualState;
@property(nonatomic) long long paletteVisualState; // @synthesize paletteVisualState=_paletteVisualState;
@property(nonatomic) long long paletteDraggingBehavior; // @synthesize paletteDraggingBehavior=_paletteDraggingBehavior;
@property(nonatomic) long long dockingAppearance; // @synthesize dockingAppearance=_dockingAppearance;
@property(retain, nonatomic) UITapGestureRecognizer *tapToExpandPaletteFromMinimizedGestureRecognizer; // @synthesize tapToExpandPaletteFromMinimizedGestureRecognizer=_tapToExpandPaletteFromMinimizedGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *paletteCenterYConstraint; // @synthesize paletteCenterYConstraint=_paletteCenterYConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteCenterXConstraint; // @synthesize paletteCenterXConstraint=_paletteCenterXConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteRightConstraint; // @synthesize paletteRightConstraint=_paletteRightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteLeftConstraint; // @synthesize paletteLeftConstraint=_paletteLeftConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteBottomConstraint; // @synthesize paletteBottomConstraint=_paletteBottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteTopConstraint; // @synthesize paletteTopConstraint=_paletteTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteHeightConstraint; // @synthesize paletteHeightConstraint=_paletteHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *paletteWidthConstraint; // @synthesize paletteWidthConstraint=_paletteWidthConstraint;
@property(nonatomic) double paletteViewCompactHeight; // @synthesize paletteViewCompactHeight=_paletteViewCompactHeight;
@property(nonatomic) __weak id <PKPaletteHostViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) PKPaletteView *paletteView; // @synthesize paletteView=_paletteView;
- (void).cxx_destruct;
- (void)paletteView:(id)arg1 didChangeAnnotationSupport:(_Bool)arg2;
- (struct CGSize)regularPaletteSize;
- (void)paletteView:(id)arg1 didToggleAutoHideOption:(_Bool)arg2;
- (_Bool)isDraggingPalette;
@property(readonly, nonatomic) UIView *hostingView;
- (_Bool)_shouldBeCompact;
- (void)traitCollectionDidChange:(id)arg1;
- (void)_paletteDidSettle;
- (void)_paletteDidChangeSizeForVisualState:(long long)arg1;
- (void)_paletteWillChangeSizeForVisualState:(long long)arg1;
- (_Bool)_isPaletteAlmostFinishedRotating;
- (_Bool)_isPaletteRotating;
- (_Bool)_isPaletteAlmostFinishedMinimizing;
- (_Bool)_isPaletteAlmostMinimized;
- (_Bool)_isPaletteMinimizing;
- (_Bool)_isPaletteAnimating;
- (struct CGSize)_paletteSizeForVisualState:(long long)arg1;
- (struct CGSize)_minimizedPaletteSize;
- (struct CGSize)_regularPaletteSize;
- (void)_animatePaletteSizeForVisualState:(long long)arg1;
- (void)_performAnimated:(_Bool)arg1 tracking:(_Bool)arg2 animations:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_panGestureHandler:(id)arg1;
- (void)_deactivatePaletteEdgeConstraints;
- (void)_activatePaletteCenterConstraints;
- (void)_deactivatePaletteCenterConstraints;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_tapToExpandPaletteFromMinimizedGestureHandler:(id)arg1;
- (void)_paletteDidDockToCorner:(unsigned long long)arg1;
- (void)_paletteWillDockToCorner:(unsigned long long)arg1;
- (void)_updateConstraintsToDockPaletteToCorner:(unsigned long long)arg1;
- (void)_dockPaletteToCorner:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)_paletteDidDockToEdge:(unsigned long long)arg1;
- (void)_paletteWillDockToEdge:(unsigned long long)arg1;
- (void)_updateConstraintsToDockPaletteToEdge:(unsigned long long)arg1;
- (void)_dockPaletteToEdge:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)fixToEdge:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateConstraints;
- (void)layoutSubviews;
- (void)_upatePaletteViewSizeConstraints;
- (void)setCommonPaletteViewProperties;
- (void)adaptAppearanceToExpandFromAnyCorner;
- (void)adaptAppearanceToDockToAnyCorner;
- (void)adaptAppearanceToDockToAnyEdge;
- (void)adaptAppearanceToHorizontalCompactSize;
- (void)didMoveToWindow;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

