//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Preferences/PSTableCell.h>

@class NSLayoutConstraint, UILabel;

@interface ActiveDeviceLinkCell : PSTableCell
{
    UILabel *_fromLabel;
    UILabel *_deviceNameLabel;
    UILabel *_detailsLabel;
    NSLayoutConstraint *_detailsHeightContraint;
    NSLayoutConstraint *_fromLabelLeadingConstraint;
}

+ (long long)cellStyle;
- (void).cxx_destruct;
@property(retain, nonatomic) NSLayoutConstraint *fromLabelLeadingConstraint; // @synthesize fromLabelLeadingConstraint=_fromLabelLeadingConstraint;
@property(retain, nonatomic) NSLayoutConstraint *detailsHeightContraint; // @synthesize detailsHeightContraint=_detailsHeightContraint;
@property(retain, nonatomic) UILabel *detailsLabel; // @synthesize detailsLabel=_detailsLabel;
@property(retain, nonatomic) UILabel *deviceNameLabel; // @synthesize deviceNameLabel=_deviceNameLabel;
@property(retain, nonatomic) UILabel *fromLabel; // @synthesize fromLabel=_fromLabel;
- (void)layoutSubviews;
- (void)setupConstraints;
- (void)setupSubviews;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;

@end

