//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstallCoordination/IXDataPromise.h>

#import "NSSecureCoding.h"

@class IXOwnedDataPromiseSeed, NSURL;

@interface IXOwnedDataPromise : IXDataPromise <NSSecureCoding>
{
    NSURL *_stagedPath;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSURL *stagingBaseDir; // @dynamic stagingBaseDir;
- (Class)seedClass;
@property(retain, nonatomic) NSURL *stagedPath; // @synthesize stagedPath=_stagedPath;

// Remaining properties
@property(retain, nonatomic) IXOwnedDataPromiseSeed *seed; // @dynamic seed;

@end

