//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, UICollectionViewDropProposal;

__attribute__((visibility("hidden")))
@interface _UIDragDestinationControllerDropProposalState : NSObject
{
    _Bool _didDrop;
    UICollectionViewDropProposal *_proposal;
    NSIndexPath *_indexPath;
}

@property(nonatomic) _Bool didDrop; // @synthesize didDrop=_didDrop;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) UICollectionViewDropProposal *proposal; // @synthesize proposal=_proposal;
- (void).cxx_destruct;
- (_Bool)_hasDropActionTarget;
@property(readonly, nonatomic) NSIndexPath *effectiveIndexPath;
- (void)updateFromDropProposal:(id)arg1;
- (void)didPerformDrop;
- (id)description;
- (id)init;

@end

