//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TSUtility/TSUColor.h>

#import <TSStyles/TSSPreset-Protocol.h>
#import <TSStyles/TSSPresetSource-Protocol.h>
#import <TSStyles/TSSPropertyCommandSerializing-Protocol.h>
#import <TSStyles/TSSPropertyValueArchiving-Protocol.h>

@class NSString;

@interface TSUColor (TSSArchivingUtilities) <TSSPropertyValueArchiving, TSSPropertyCommandSerializing, TSSPreset, TSSPresetSource>
+ (id)instanceWithArchive:(const struct Message *)arg1 unarchiver:(id)arg2;
+ (void)bootstrapPresetsOfKind:(id)arg1 inTheme:(id)arg2 alternate:(int)arg3;
+ (id)presetKinds;
+ (id)p_defaultPresetColors:(int)arg1;
- (void)saveToPropertyCommandMessage:(struct Message *)arg1 archiver:(id)arg2;
- (id)initFromPropertyCommandMessage:(const struct Message *)arg1 unarchiver:(id)arg2;
-     // Error parsing type: v32@0:8^{Color=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}ffffffffiif}16@24, name: saveToArchive:archiver:
-     // Error parsing type: @32@0:8r^{Color=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}ffffffffiif}16@24, name: initWithArchive:unarchiver:
@property(readonly, nonatomic) NSString *presetKind;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

