//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PHAsset;

@interface _NTKNewPhoto : NSObject
{
    PHAsset *_asset;
    unsigned long long _subsampleFactor;
    struct CGRect _crop;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long subsampleFactor; // @synthesize subsampleFactor=_subsampleFactor;
@property(nonatomic) struct CGRect crop; // @synthesize crop=_crop;
@property(retain, nonatomic) PHAsset *asset; // @synthesize asset=_asset;

@end

