//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKEnumeratedEditOption.h>

@interface NTKKaleidoscopeStyleOption : NTKEnumeratedEditOption
{
}

+ (id)_nameLocalizationKeyForValue:(unsigned long long)arg1;
+ (id)_snapshotKeyForValue:(unsigned long long)arg1;
+ (id)_orderedValues;
+ (long long)indexForStyle:(unsigned long long)arg1;
+ (id)optionWithStyle:(unsigned long long)arg1;
- (id)_valueToFaceBundleStringDict;
@property(readonly, nonatomic) unsigned long long style;
- (long long)swatchStyle;

@end

