//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NanoTimeKitCompanion/NTKRichComplicationProgressView.h>

@class NTKRichComplicationRingView;

@interface NTKRichComplicationRingProgressView : NTKRichComplicationProgressView
{
    double _curveWidth;
    NTKRichComplicationRingView *_backgroundView;
    NTKRichComplicationRingView *_foregroundView;
    _Bool _clockwise;
    _Bool _hidesOverlapShadow;
}

@property(nonatomic) _Bool hidesOverlapShadow; // @synthesize hidesOverlapShadow=_hidesOverlapShadow;
@property(nonatomic) _Bool clockwise; // @synthesize clockwise=_clockwise;
- (void).cxx_destruct;
- (id)initWithCurveWidth:(double)arg1 padding:(double)arg2 overlapStrokeWidth:(double)arg3 forDevice:(id)arg4;
- (id)initWithCurveWidth:(double)arg1 padding:(double)arg2 forDevice:(id)arg3;

@end

