//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "_SFAppleConnectExtensionContentScriptMessageReceiver.h"
#import "_SFAppleConnectExtensionPageDelegate.h"

@class NSString, WKWebView, _WKRemoteObjectInterface;

@interface _SFAppleConnectExtensionPageController : NSObject <_SFAppleConnectExtensionContentScriptMessageReceiver, _SFAppleConnectExtensionPageDelegate>
{
    id <_SFAppleConnectExtensionMessageReceiver> _appleConnectExtensionMessageReceiver;
    _WKRemoteObjectInterface *_contentScriptMessageReceiverInterface;
    WKWebView *_webView;
    id <_SFAppleConnectExtensionUIDelegate> _delegate;
}

@property(nonatomic) __weak id <_SFAppleConnectExtensionUIDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dismissExtensionViewController:(id)arg1;
- (void)presentExtensionViewController:(id)arg1;
- (void)dispatchMessageToContentScriptWithName:(id)arg1 userInfo:(id)arg2;
- (id)_appleConnectExtensionMessageReceiver;
- (void)dispatchMessageFromContentScript:(id)arg1 userInfo:(id)arg2;
- (void)invalidate;
- (id)initWithWebView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

