//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/NSObject-Protocol.h>

@class NSData, NSString, _SFQuickLookDocument;

@protocol _SFQuickLookDocumentSource <NSObject>
- (NSString *)suggestedFileExtensionForQuickLookDocument:(_SFQuickLookDocument *)arg1;
- (NSString *)suggestedFileNameForQuickLookDocument:(_SFQuickLookDocument *)arg1;
- (NSData *)dataForQuickLookDocument:(_SFQuickLookDocument *)arg1;
@end

