//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HDSourceEntity, NSString;

@interface HDSourceRevision : NSObject
{
    HDSourceEntity *_sourceEntity;
    NSString *_version;
    NSString *_productType;
    CDStruct_4bb15e50 _operatingSystemVersion;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) CDStruct_77932685 operatingSystemVersion; // @synthesize operatingSystemVersion=_operatingSystemVersion;
@property(readonly, nonatomic) NSString *productType; // @synthesize productType=_productType;
@property(readonly, nonatomic) NSString *version; // @synthesize version=_version;
@property(readonly, nonatomic) HDSourceEntity *sourceEntity; // @synthesize sourceEntity=_sourceEntity;
- (id)initWithSource:(id)arg1 version:(id)arg2 productType:(id)arg3 operatingSystemVersion:(CDStruct_77932685)arg4;

@end

