//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CATransformLayer.h>

@class CAGradientLayer, CALayer;

@interface _ExplorerDotLayer : CATransformLayer
{
    CALayer *_contentLayer;
    CALayer *_lidLayer;
    CAGradientLayer *_overlayLayer;
}

@property(readonly, nonatomic) CAGradientLayer *overlayLayer; // @synthesize overlayLayer=_overlayLayer;
@property(readonly, nonatomic) CALayer *lidLayer; // @synthesize lidLayer=_lidLayer;
@property(readonly, nonatomic) CALayer *contentLayer; // @synthesize contentLayer=_contentLayer;
- (void).cxx_destruct;
- (void)layoutSublayers;
- (id)init;

@end

