//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <NanoTimeKit/NTKRelevanceProvider.h>

@interface NTKWalletPassStyleRelevanceProvider : NTKRelevanceProvider
{
    int _style;
}

@property(readonly, nonatomic) int style; // @synthesize style=_style;
- (id)description;
- (unsigned int)_hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPassStyle:(int)arg1;

@end

