//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GameCenterUI/GKCollectionViewCell.h>

@class GKGame, GKGameRecord, UIImageView, UILabel;

@interface GKBaseGameCell : GKCollectionViewCell
{
    UIImageView *_iconView;
    UILabel *_nameLabel;
}

@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
- (void)prepareForReuse;
- (void)didUpdateModel;
- (void)setRepresentedItem:(id)arg1;
@property(retain, nonatomic) GKGame *game;
@property(retain, nonatomic) GKGameRecord *gameRecord;
- (struct CGRect)alignmentRectForText;
- (void)dealloc;

@end

