//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSString, _CPSearchResultForFeedback;

@protocol _CPResultGradingFeedback <NSObject>
@property(readonly, nonatomic) NSData *jsonData;
@property(readonly, nonatomic) _Bool hasTextFeedback;
@property(copy, nonatomic) NSString *textFeedback;
@property(readonly, nonatomic) _Bool hasGrade;
@property(nonatomic) int grade;
@property(readonly, nonatomic) _Bool hasResult;
@property(retain, nonatomic) _CPSearchResultForFeedback *result;
@property(readonly, nonatomic) _Bool hasTimestamp;
@property(nonatomic) unsigned long long timestamp;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
@end

