//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HMFoundation/HMFObject.h>

#import <HomeKitBackingStore/NSCopying-Protocol.h>
#import <HomeKitBackingStore/NSMutableCopying-Protocol.h>

@class HMBLocalZone, HMFUnfairLock, HMFVersion, NSMapTable;
@protocol HMBMirrorProtocol;

@interface HMBModelContainer : HMFObject <NSMutableCopying, NSCopying>
{
    HMFVersion *_legacyDataVersion;
    HMFVersion *_dataVersion;
    HMFUnfairLock *_propertyLock;
    NSMapTable *_queryFieldsCache;
    HMBLocalZone *_localZone;
    id <HMBMirrorProtocol> _mirror;
    NSMapTable *_classToNameTransform;
    NSMapTable *_nameToClassTransform;
    NSMapTable *_objectPropertyHashLookup;
    NSMapTable *_classReadOnlyVersionCache;
    NSMapTable *_classUnavailableVersionCache;
}

+ (id)decodeAsNSDictionary:(id)arg1 error:(id *)arg2;
+ (id)encodeAsNSDictionary:(id)arg1 error:(id *)arg2;
+ (id)decodeAsOPACK:(id)arg1 error:(id *)arg2;
+ (id)encodeAsOPACK:(id)arg1 error:(id *)arg2;
+ (id)internalAllowedTypes;
+ (id)allowedTypes;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMapTable *classUnavailableVersionCache; // @synthesize classUnavailableVersionCache=_classUnavailableVersionCache;
@property(retain, nonatomic) NSMapTable *classReadOnlyVersionCache; // @synthesize classReadOnlyVersionCache=_classReadOnlyVersionCache;
@property(retain, nonatomic) NSMapTable *objectPropertyHashLookup; // @synthesize objectPropertyHashLookup=_objectPropertyHashLookup;
@property(copy, nonatomic) NSMapTable *nameToClassTransform; // @synthesize nameToClassTransform=_nameToClassTransform;
@property(copy, nonatomic) NSMapTable *classToNameTransform; // @synthesize classToNameTransform=_classToNameTransform;
@property(readonly, nonatomic) __weak id <HMBMirrorProtocol> mirror; // @synthesize mirror=_mirror;
@property(readonly, nonatomic) __weak HMBLocalZone *localZone; // @synthesize localZone=_localZone;
@property(readonly, nonatomic) NSMapTable *queryFieldsCache; // @synthesize queryFieldsCache=_queryFieldsCache;
@property(readonly, nonatomic) HMFUnfairLock *propertyLock; // @synthesize propertyLock=_propertyLock;
@property(readonly, copy, nonatomic) HMFVersion *dataVersion; // @synthesize dataVersion=_dataVersion;
@property(readonly, copy, nonatomic) HMFVersion *legacyDataVersion; // @synthesize legacyDataVersion=_legacyDataVersion;
- (void)updateMirror:(id)arg1;
- (void)updateLocalZone:(id)arg1;
- (id)schemaHashForModel:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)modelFromData:(id)arg1 encoding:(unsigned int)arg2 storageLocation:(unsigned int)arg3 error:(id *)arg4;
- (id)modelFromData:(id)arg1 encoding:(unsigned int)arg2 storageLocation:(unsigned int)arg3 type:(id)arg4 error:(id *)arg5;
- (id)modelFromDictionary:(id)arg1 storageLocation:(unsigned int)arg2 typeName:(id)arg3 error:(id *)arg4;
- (id)dataFromModel:(id)arg1 encoding:(unsigned int)arg2 storageLocation:(unsigned int)arg3 updatedModelIDs:(id)arg4 error:(id *)arg5;
- (Class)modelClassForTypeName:(id)arg1;
- (id)typeNameForModelClass:(Class)arg1;
- (unsigned int)bestModelEncodingForStorageLocation:(unsigned int)arg1;
- (id)unavailableVersionsForModelClass:(Class)arg1;
- (id)readOnlyVersionsForModelClass:(Class)arg1;
- (id)initWithDataVersion:(id)arg1 legacyDataVersion:(id)arg2;
- (id)init;

@end

