//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBSDisplayLayoutElement.h"

#import "SBSDisplayLayoutElement.h"

@class NSString;

@interface FBSDisplayLayoutElement (SBSDisplayLayoutElement) <SBSDisplayLayoutElement>
@property(readonly, nonatomic) long long layoutRole;
@property(readonly, nonatomic, getter=isSpringBoardElement) _Bool springBoardElement;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

