//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppleMediaServices/AMSFrozenBagValue.h>

@class AMSPromise;

__attribute__((visibility("hidden")))
@interface AMSBridgedBagValue : AMSFrozenBagValue
{
    AMSPromise *_valuePromise;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AMSPromise *valuePromise; // @synthesize valuePromise=_valuePromise;
- (void)valueWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithKey:(id)arg1 valueType:(unsigned int)arg2 valuePromise:(id)arg3;

@end

