//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <TVKit/UIGestureRecognizerDelegate-Protocol.h>

@class NSString, TVRelatedContent, UIGestureRecognizer;
@protocol TVRelatedContentViewControllerDelegate;

@interface TVRelatedContentViewController : UIViewController <UIGestureRecognizerDelegate>
{
    id <TVRelatedContentViewControllerDelegate> _delegate;
    UIViewController *_primaryViewController;
    TVRelatedContent *_relatedContent;
    unsigned long long _preferredDisplayMode;
    unsigned long long _displayMode;
    UIGestureRecognizer *_interactionGestureRecognizer;
    unsigned long long _numberOfAppearanceTransitions;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long numberOfAppearanceTransitions; // @synthesize numberOfAppearanceTransitions=_numberOfAppearanceTransitions;
@property(retain, nonatomic) UIGestureRecognizer *interactionGestureRecognizer; // @synthesize interactionGestureRecognizer=_interactionGestureRecognizer;
@property(readonly, nonatomic) unsigned long long displayMode; // @synthesize displayMode=_displayMode;
@property(nonatomic) unsigned long long preferredDisplayMode; // @synthesize preferredDisplayMode=_preferredDisplayMode;
@property(retain, nonatomic) TVRelatedContent *relatedContent; // @synthesize relatedContent=_relatedContent;
@property(retain, nonatomic) UIViewController *primaryViewController; // @synthesize primaryViewController=_primaryViewController;
@property(nonatomic) __weak id <TVRelatedContentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidLoad;
- (void)loadView;
- (id)preferredFocusEnvironments;
- (struct CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(struct CGSize)arg2;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)setPreferredDisplayMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setRelatedContent:(id)arg1 animated:(_Bool)arg2;
- (void)_menuButtonTapRecognized:(id)arg1;
- (void)_userInteractionBegan:(id)arg1;
- (unsigned long long)_actualDisplayModeForPreferredDisplayMode:(unsigned long long)arg1 withRelatedContent:(id)arg2;
- (void)_setDisplayMode:(unsigned long long)arg1 relatedContent:(id)arg2 animated:(_Bool)arg3;
- (id)_visibleViewControllers;
- (void)_augmentOverrideTraitCollectionForChildViewController:(id)arg1 withContentType:(long long)arg2;
- (id)_viewControllersForDisplayMode:(unsigned long long)arg1 withRelatedContent:(id)arg2;
- (void)_performViewAnimations:(CDUnknownBlockType)arg1 animated:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (double)_heightForContentType:(long long)arg1 withRelatedContent:(id)arg2 displayMode:(unsigned long long)arg3 parentContainerSize:(struct CGSize)arg4;
- (double)_widthForContentType:(long long)arg1 withRelatedContent:(id)arg2 displayMode:(unsigned long long)arg3 parentContainerSize:(struct CGSize)arg4;
- (id)_viewControllerForContentType:(long long)arg1 withRelatedContent:(id)arg2;
- (long long)_contentTypeForContainer:(id)arg1 withRelatedContent:(id)arg2;
- (double)_presentationProgressForDisplayMode:(unsigned long long)arg1;
- (void)_didTransitionToDisplayMode:(unsigned long long)arg1;
- (void)_willTransitionToDisplayMode:(unsigned long long)arg1;
- (void)_decrementNumberOfAppearanceTransitions;
- (void)_incrementNumberOfAppearanceTransitions;
- (id)_relatedContentView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

