//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MTLCapture/CaptureMTLObject-Protocol.h>
#import <MTLCapture/MTLRenderPipelineStateSPI-Protocol.h>

@class CaptureMTLDevice, MTLDebugInstrumentationData, MTLRenderPipelineDescriptor, NSString;
@protocol MTLDevice, MTLRenderPipelineState, MTLRenderPipelineStateSPI;

@interface CaptureMTLRenderPipelineState : NSObject <MTLRenderPipelineStateSPI, CaptureMTLObject>
{
    id <MTLRenderPipelineStateSPI> _baseObject;
    CaptureMTLDevice *_captureDevice;
    // Error parsing type: ^{GTTraceContext={_opaque_pthread_mutex_t=q[56c]}^{GTTraceStore}AQAQ^{apr_hash_t}^(FreeNode)Ai^{GTTraceStream}{GTTraceStoreList=^(GTTraceStoreNode)^(GTTraceStoreNode)AiAi}}, name: _traceContext
    // Error parsing type: ^{GTTraceStream=QQQ^{GTTraceMemPool}{GTTraceStoreList=^(GTTraceStoreNode)^(GTTraceStoreNode)AiAi}AQ}, name: _traceStream
    MTLRenderPipelineDescriptor *_descriptor;
}

- (void).cxx_destruct;
@property(copy, nonatomic) MTLRenderPipelineDescriptor *descriptor; // @synthesize descriptor=_descriptor;
- (id)newVertexShaderDebugInfo;
- (id)newFragmentShaderDebugInfo;
@property(readonly) unsigned long long uniqueIdentifier;
@property(readonly) _Bool supportIndirectCommandBuffers;
@property(nonatomic) unsigned long long resourceIndex;
@property(readonly) NSString *label;
@property(readonly) id <MTLDevice> device;
- (_Bool)conformsToProtocol:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
@property(readonly, copy) NSString *description;
- (id)forwardingTargetForSelector:(SEL)arg1;
@property(readonly) unsigned long long streamReference;
// Error parsing type for property traceStream:
// Property attributes: T^{GTTraceStream=QQQ^{GTTraceMemPool}{GTTraceStoreList=^(GTTraceStoreNode)^(GTTraceStoreNode)AiAi}AQ},R

// Error parsing type for property traceContext:
// Property attributes: T^{GTTraceContext={_opaque_pthread_mutex_t=q[56c]}^{GTTraceStore}AQAQ^{apr_hash_t}^(FreeNode)Ai^{GTTraceStream}{GTTraceStoreList=^(GTTraceStoreNode)^(GTTraceStoreNode)AiAi}},R

- (void)touch;
- (void)dealloc;
@property(readonly) id <MTLRenderPipelineState> baseObject;
- (void)swapObject:(id)arg1;
- (id)initWithBaseObject:(id)arg1 captureDevice:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, retain, nonatomic) MTLDebugInstrumentationData *fragmentDebugInstrumentationData;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, retain, nonatomic) MTLDebugInstrumentationData *vertexDebugInstrumentationData;

@end

