//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TSPersistence/TSPReader.h>

#import <TSPersistence/TSPDatabaseUnarchiverDelegate-Protocol.h>

@class NSHashTable, NSObject, NSString, TSPComponent, TSPDatabase;
@protocol OS_dispatch_queue;

@interface TSPDatabaseReader : TSPReader <TSPDatabaseUnarchiverDelegate>
{
    NSObject<OS_dispatch_queue> *_databaseQueue;
    TSPDatabase *_database;
    unsigned long long _databaseVersion;
    unordered_map_38045d47 _readIdentifiers;
    NSHashTable *_datas;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (set_713dd2e1 *)filterIdentifiers:(const set_713dd2e1 *)arg1;
- (id)objectUUIDMap;
-     // Error parsing type: @24@0:8r^{DatabaseDataArchive=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}{ArenaStringPtr=^{basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >}}{ArenaStringPtr=^{basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >}}^{Reference}QIB}16, name: filenameFromOldDataArchive:
-     // Error parsing type: @24@0:8r^{DatabaseDataArchive=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}{ArenaStringPtr=^{basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >}}{ArenaStringPtr=^{basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >}}^{Reference}QIB}16, name: dataForOldDataArchive:
- (struct Message *)newImageDataMessageForDatabaseObject:(id)arg1;
- (struct Message *)newDataMessageForDatabaseObject:(id)arg1;
- (void)enumerateDataAppRelativePathsUsingBlock:(CDUnknownBlockType)arg1;
-     // Error parsing type: @24@0:8r^{DatabaseDataArchive=^^?{InternalMetadataWithArena=^v}{HasBits<1>=[1I]}{CachedSize={atomic<int>={__cxx_atomic_impl<int, std::__1::__cxx_atomic_base_impl<int> >=Ai}}}{ArenaStringPtr=^{basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >}}{ArenaStringPtr=^{basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >}}^{Reference}QIB}16, name: appRelativePathForOldDataArchive:
- (void)resolveReferences;
- (_Bool)validateObjectIdentifierForObject:(id)arg1;
- (void)didUnarchiveObject:(id)arg1 withUnarchiver:(id)arg2;
- (id)newUnarchiverWithDatabaseObject:(id)arg1;
- (void)unarchiveObjectWithIdentifierAsync:(long long)arg1;
- (void)beginReadingWithCompletionQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithComponent:(id)arg1 finalizeHandlerQueue:(id)arg2 delegate:(id)arg3 database:(id)arg4 databaseVersion:(unsigned long long)arg5;
- (id)initWithComponent:(id)arg1 finalizeHandlerQueue:(id)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) _Bool canRetainObjectReferencedByWeakLazyReference;
@property(readonly, nonatomic) TSPComponent *component;
@property(readonly, nonatomic) long long componentIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool didFinishResolvingReferences;
@property(readonly, nonatomic) unsigned long long fileFormatVersion;
@property(readonly, nonatomic) _Bool hasDocumentVersionUUID;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isCrossAppPaste;
@property(readonly, nonatomic) _Bool isCrossDocumentPaste;
@property(readonly, nonatomic) long long sourceType;
@property(readonly) Class superclass;

@end

