//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DoNotDisturbServer/DNDSBackingStoreDelegate-Protocol.h>
#import <DoNotDisturbServer/DNDSModeAssertionQuerying-Protocol.h>
#import <DoNotDisturbServer/DNDSModeAssertionUpdating-Protocol.h>
#import <DoNotDisturbServer/DNDSSysdiagnoseDataProvider-Protocol.h>

@class DNDSClientDetailsProvider, DNDSModeAssertionStore, NSString;
@protocol DNDSBackingStore;

@interface DNDSModeAssertionManager : NSObject <DNDSBackingStoreDelegate, DNDSSysdiagnoseDataProvider, DNDSModeAssertionQuerying, DNDSModeAssertionUpdating>
{
    id <DNDSBackingStore> _backingStore;
    DNDSModeAssertionStore *_store;
    DNDSClientDetailsProvider *_clientDetailsProvider;
    struct os_unfair_lock_s _storeLock;
}

- (void).cxx_destruct;
- (_Bool)_saveDataToBackingStoreWithError:(id *)arg1;
- (void)_loadDataFromBackingStore;
- (id)clientDetailsForClientIdentifier:(id)arg1;
- (id)sysdiagnoseDataForDate:(id)arg1;
@property(readonly, copy, nonatomic) NSString *sysdiagnoseDataIdentifier; // @dynamic sysdiagnoseDataIdentifier;
- (id)backingStore:(id)arg1 migrateDictionaryRepresentation:(id)arg2 fromVersionNumber:(unsigned int)arg3 toVersionNumber:(unsigned int)arg4;
- (id)updateModeAssertionsWithContextHandler:(CDUnknownBlockType)arg1 error:(id *)arg2;
- (id)modeAssertionInvalidationsMatchingPredicate:(id)arg1;
- (id)modeAssertionsMatchingPredicate:(id)arg1;
- (void)dealloc;
- (id)initWithBackingStore:(id)arg1 clientDetailsProvider:(id)arg2;
- (id)initWithBackingStoreURL:(id)arg1 clientDetailsProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

