//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <ComponentKit/CKComponentDebugReflowListener-Protocol.h>
#import <ComponentKit/CKComponentStateListener-Protocol.h>

@class CKComponent, NSSet, NSString;
@protocol CKComponentHostingViewDelegate, CKComponentSizeRangeProviding;

@interface CKComponentHostingView : UIView <CKComponentStateListener, CKComponentDebugReflowListener>
{
    Class _componentProvider;
    id <CKComponentSizeRangeProviding> _sizeRangeProvider;
    struct CKComponentHostingViewInputs _pendingInputs;
    struct CKComponentBoundsAnimation _boundsAnimation;
    CKComponent *_component;
    _Bool _componentNeedsUpdate;
    unsigned long long _requestedUpdateMode;
    struct CKComponentLayout _mountedLayout;
    NSSet *_mountedComponents;
    _Bool _scheduledAsynchronousComponentUpdate;
    _Bool _isSynchronouslyUpdatingComponent;
    _Bool _isMountingComponent;
    id <CKComponentHostingViewDelegate> _delegate;
    UIView *_containerView;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <CKComponentHostingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_synchronouslyUpdateComponentIfNeeded;
- (void)_applyResult:(const struct CKBuildComponentResult *)arg1;
- (void)_scheduleAsynchronousUpdate;
- (void)_asynchronouslyUpdateComponentIfNeeded;
- (void)_setNeedsUpdateWithMode:(unsigned long long)arg1;
- (void)didReceiveReflowComponentsRequest;
- (void)componentScopeHandleWithIdentifier:(int)arg1 rootIdentifier:(int)arg2 didReceiveStateUpdate:(CDUnknownBlockType)arg3 mode:(unsigned long long)arg4;
- (const struct CKComponentLayout *)mountedLayout;
- (void)updateContext:(id)arg1 mode:(unsigned long long)arg2;
- (void)updateModel:(id)arg1 mode:(unsigned long long)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithComponentProvider:(Class)arg1 sizeRangeProvider:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

