//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager, CLRegion, NSArray, NSDictionary, NSError, _CLRangingPeer;

@protocol CLLocationManagerDelegateInternal <CLLocationManagerDelegate>

@optional
- (void)locationManager:(CLLocationManager *)arg1 rangingDidFailForPeer:(_CLRangingPeer *)arg2 withError:(NSError *)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didStopRangingForPeer:(_CLRangingPeer *)arg2;
- (void)locationManager:(CLLocationManager *)arg1 didStartRangingForPeer:(_CLRangingPeer *)arg2;
- (void)locationManager:(CLLocationManager *)arg1 didRangePeers:(NSArray *)arg2;
- (void)locationManager:(CLLocationManager *)arg1 didExitRegion:(CLRegion *)arg2 withLocation:(CLLocation *)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didEnterRegion:(CLRegion *)arg2 withLocation:(CLLocation *)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didFailFindingPlacemarkForLocation:(CLLocation *)arg2 withError:(NSError *)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didFindPlacemark:(NSDictionary *)arg2 forLocation:(CLLocation *)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didChangeStatusForTechnology:(int)arg2 active:(_Bool)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didChangeAppStatusFor:(NSDictionary *)arg2;
- (void)locationManager:(CLLocationManager *)arg1 didReceiveApproval:(_Bool)arg2;
- (void)locationManager:(CLLocationManager *)arg1 didRecordHistoricLocation:(CLLocation *)arg2 forInterval:(double)arg3;
- (void)locationManager:(CLLocationManager *)arg1 didUpdateToLocation:(CLLocation *)arg2 fromLocation:(CLLocation *)arg3 usingSupportInfo:(NSDictionary *)arg4;
@end

