//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKitCore/UIView.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface _UIPreviewPresentationEffectView : UIView
{
    _Bool _shouldRasterizeForTransition;
    UIColor *_shadowColor;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool shouldRasterizeForTransition; // @synthesize shouldRasterizeForTransition=_shouldRasterizeForTransition;
@property(copy, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;
@property(nonatomic) float shadowRadius;
@property(nonatomic) struct CGSize shadowOffset;
@property(nonatomic) float shadowAlpha;
@property(nonatomic) float cornerRadius;
@property(nonatomic) float blurRadius; // @dynamic blurRadius;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

