//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKitCore/UIStatusBarButtonActionItemView.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarAppIconItemView : UIStatusBarButtonActionItemView
{
}

- (id)highlightImage;
- (id)contentsImage;
- (id)_appBundleIdentifier;

@end

