//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UILabel;

@interface PKPerformActionSelectItemCell : UITableViewCell
{
    UILabel *_descriptionLabel;
    UILabel *_amountLabel;
    NSString *_descriptionText;
    NSString *_amountText;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *amountText; // @synthesize amountText=_amountText;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
- (void)_addSubviews;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

