//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <GeoServices/GEOGizmoXPCInterface-Protocol.h>

@class GEOApplicationAuditToken, GEODataRequestThrottlerToken, GEOMapServiceTraits, GEOPDPlaceRequest, GEOPlaceDataRequester, NSXPCConnection, geo_isolater;

__attribute__((visibility("hidden")))
@interface _GEOCompanionPlaceDataRequesterOp : NSObject <GEOGizmoXPCInterface>
{
    geo_isolater *_isolation;
    GEOPDPlaceRequest *_request;
    GEOMapServiceTraits *_traits;
    GEOApplicationAuditToken *_auditToken;
    GEODataRequestThrottlerToken *_throttleToken;
    double _timeout;
    GEOPlaceDataRequester *_networkRequester;
    NSXPCConnection *_connection;
    _Bool _canceled;
    CDUnknownBlockType _completionHandler;
}

- (void).cxx_destruct;
- (void)didChangePairedDeviceReachability:(_Bool)arg1;
- (void)cancel;
- (void)_sendRequestToNetwork;
- (void)_sendRequestToCompanion;
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_sendResponse:(id)arg1;
- (void)_sendError:(id)arg1;
- (void)_cleanup;
- (void)dealloc;
- (id)initWithRequest:(id)arg1 auditToken:(id)arg2 timeout:(double)arg3 traits:(id)arg4 throttleToken:(id)arg5;

@end

