//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOCapturedState.h>

@interface GEODataSessionTaskState : GEOCapturedState
{
    long _rawPointer;
    unsigned int _taskIdentifier;
    long _completedSubtaskPointer;
    long _urlTaskPointer;
    long _xpcTaskPointer;
    double _now;
    double _startTime;
    double _endTime;
    int _requestKind;
    unsigned int _outgoingPayloadSize;
}

+ (const char *)decoderType;
+ (_Bool)supportsSecureCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

