//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOPDClientRankingFeatureFunctionTypeDiscrete, GEOPDClientRankingFeatureFunctionTypeLinear, GEOPDClientRankingFeatureTypeResult, GEOPDClientRankingFeatureTypeSource, PBDataReader, PBUnknownFields;

__attribute__((visibility("hidden")))
@interface GEOPDClientRankingFeatureMetadata : PBCodable <NSCopying>
{
    PBDataReader *_reader;
    PBUnknownFields *_unknownFields;
    GEOPDClientRankingFeatureTypeResult *_featureTypeResult;
    GEOPDClientRankingFeatureTypeSource *_featureTypeSource;
    GEOPDClientRankingFeatureFunctionTypeDiscrete *_functionTypeDiscrete;
    GEOPDClientRankingFeatureFunctionTypeLinear *_functionTypeLinear;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    struct os_unfair_lock_s _readerLock;
    int _featureType;
    int _functionType;
    struct {
        unsigned int has_featureType:1;
        unsigned int has_functionType:1;
        unsigned int read_unknownFields:1;
        unsigned int read_featureTypeResult:1;
        unsigned int read_featureTypeSource:1;
        unsigned int read_functionTypeDiscrete:1;
        unsigned int read_functionTypeLinear:1;
        unsigned int wrote_unknownFields:1;
        unsigned int wrote_featureTypeResult:1;
        unsigned int wrote_featureTypeSource:1;
        unsigned int wrote_functionTypeDiscrete:1;
        unsigned int wrote_functionTypeLinear:1;
        unsigned int wrote_featureType:1;
        unsigned int wrote_functionType:1;
    } _flags;
}

+ (_Bool)isValid:(id)arg1;
- (void).cxx_destruct;
- (void)clearUnknownFields:(_Bool)arg1;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned int)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (void)readAll:(_Bool)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(retain, nonatomic) GEOPDClientRankingFeatureFunctionTypeDiscrete *functionTypeDiscrete;
@property(readonly, nonatomic) _Bool hasFunctionTypeDiscrete;
- (void)_readFunctionTypeDiscrete;
@property(retain, nonatomic) GEOPDClientRankingFeatureFunctionTypeLinear *functionTypeLinear;
@property(readonly, nonatomic) _Bool hasFunctionTypeLinear;
- (void)_readFunctionTypeLinear;
- (int)StringAsFunctionType:(id)arg1;
- (id)functionTypeAsString:(int)arg1;
@property(nonatomic) _Bool hasFunctionType;
@property(nonatomic) int functionType;
@property(retain, nonatomic) GEOPDClientRankingFeatureTypeResult *featureTypeResult;
@property(readonly, nonatomic) _Bool hasFeatureTypeResult;
- (void)_readFeatureTypeResult;
@property(retain, nonatomic) GEOPDClientRankingFeatureTypeSource *featureTypeSource;
@property(readonly, nonatomic) _Bool hasFeatureTypeSource;
- (void)_readFeatureTypeSource;
- (int)StringAsFeatureType:(id)arg1;
- (id)featureTypeAsString:(int)arg1;
@property(nonatomic) _Bool hasFeatureType;
@property(nonatomic) int featureType;
- (id)initWithData:(id)arg1;
- (id)init;

@end

