//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <QuickLookUI/NSScrubberDataSource-Protocol.h>
#import <QuickLookUI/NSScrubberDelegate-Protocol.h>
#import <QuickLookUI/NSTouchBarDelegate-Protocol.h>

@class NSScrubber, NSString, NSTouchBar, NSTouchBarItem, QLThumbnailScrubberItemView;
@protocol QLThumbnailTouchbarControllerDelegate;

@interface QLThumbnailTouchbarController : NSObject <NSTouchBarDelegate, NSScrubberDataSource, NSScrubberDelegate>
{
    NSTouchBar *_touchBar;
    NSTouchBarItem *_pageScrubberItem;
    QLThumbnailScrubberItemView *_previouslySelectedItemView;
    NSObject<QLThumbnailTouchbarControllerDelegate> *_delegate;
}

- (void).cxx_destruct;
@property(retain) QLThumbnailScrubberItemView *previouslySelectedItemView; // @synthesize previouslySelectedItemView=_previouslySelectedItemView;
@property(nonatomic) __weak NSObject<QLThumbnailTouchbarControllerDelegate> *delegate; // @synthesize delegate=_delegate;
@property(retain) NSTouchBarItem *pageScrubberItem; // @synthesize pageScrubberItem=_pageScrubberItem;
- (void)notifyDelegateOfPageUpdate;
- (void)scrubber:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)highlightSelectedItemAtIndex:(long long)arg1;
- (id)scrubber:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsForScrubber:(id)arg1;
- (unsigned long long)currentPage;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly) NSScrubber *scrubber;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
@property(readonly) NSTouchBar *touchBar;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

