//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivityViewController.h"

@class ICDocCamDocumentInfoCollection, ICDocCamImageCache;

__attribute__((visibility("hidden")))
@interface DCActivityViewController : UIActivityViewController
{
    _Bool _ignoreAttachmentsForCopyToPasteboard;
    ICDocCamDocumentInfoCollection *_documentInfoCollection;
    ICDocCamImageCache *_imageCache;
}

@property(nonatomic) _Bool ignoreAttachmentsForCopyToPasteboard; // @synthesize ignoreAttachmentsForCopyToPasteboard=_ignoreAttachmentsForCopyToPasteboard;
@property(retain, nonatomic) ICDocCamImageCache *imageCache; // @synthesize imageCache=_imageCache;
@property(retain, nonatomic) ICDocCamDocumentInfoCollection *documentInfoCollection; // @synthesize documentInfoCollection=_documentInfoCollection;
- (void).cxx_destruct;
- (id)activityTypesThatInhibitPDFGeneration;
- (_Bool)writeGalleryPDFDataToPasteboardIfNecessaryForActivity:(id)arg1 documentInfoCollection:(id)arg2;
- (_Bool)inhibitPDFGenerationForActivityType:(id)arg1;
- (void)_performActivity:(id)arg1;

@end

