//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/_UIFocusTest.h>

@class UIWindow;

@interface _UIFocusSwipeTest : _UIFocusTest
{
    unsigned int _eventCount;
    const struct {
        double _field1;
        int _field2;
        float _field3;
        float _field4;
        float _field5;
        float _field6;
    } *_events;
    UIWindow *_window;
    int _swipeAxis;
}

@property(nonatomic) int swipeAxis; // @synthesize swipeAxis=_swipeAxis;
@property(nonatomic) __weak UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)main;
- (void)prepareWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithIdentifier:(id)arg1;

@end

