//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol _UIFocusItemDebuggable <NSObject>

@optional
- (void)_diagnoseFocusInteractionEligibilityForReport:(id <_UIDebugIssueReporting>)arg1;
- (_Bool)_shouldAlwaysDiagnoseFocusInteractionEligibility;
- (void)_diagnoseFocusabilityForReport:(id <_UIDebugIssueReporting>)arg1;
@end

