//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UICollectionLayoutGeometryGroupItemConfiguration.h"

@class NSString, UICollectionLayoutGeometry;

@interface UICollectionLayoutGeometryGroupItemConfiguration : NSObject <UICollectionLayoutGeometryGroupItemConfiguration>
{
    _Bool _heightSizedToContentHeight;
    _Bool _heightSizedToContainerHeight;
    _Bool _widthSizedToContentWidth;
    _Bool _widthSizedToContainerWidth;
    float _height;
    float _heightSizedToContainerHeightFactor;
    float _heightSizedToContainerWidthFactor;
    float _width;
    float _widthSizedToContainerWidthFactor;
    float _widthSizedToContainerHeightFactor;
    UICollectionLayoutGeometry *_layoutGeometry;
    struct UIEdgeInsets _requiredEdgeSpacing;
}

+ (id)defaultItemConfig;
@property(copy, nonatomic) UICollectionLayoutGeometry *layoutGeometry; // @synthesize layoutGeometry=_layoutGeometry;
@property(nonatomic) struct UIEdgeInsets requiredEdgeSpacing; // @synthesize requiredEdgeSpacing=_requiredEdgeSpacing;
@property(nonatomic) float widthSizedToContainerHeightFactor; // @synthesize widthSizedToContainerHeightFactor=_widthSizedToContainerHeightFactor;
@property(nonatomic) float widthSizedToContainerWidthFactor; // @synthesize widthSizedToContainerWidthFactor=_widthSizedToContainerWidthFactor;
@property(nonatomic) float width; // @synthesize width=_width;
@property(nonatomic) _Bool widthSizedToContainerWidth; // @synthesize widthSizedToContainerWidth=_widthSizedToContainerWidth;
@property(nonatomic) _Bool widthSizedToContentWidth; // @synthesize widthSizedToContentWidth=_widthSizedToContentWidth;
@property(nonatomic) float heightSizedToContainerWidthFactor; // @synthesize heightSizedToContainerWidthFactor=_heightSizedToContainerWidthFactor;
@property(nonatomic) float heightSizedToContainerHeightFactor; // @synthesize heightSizedToContainerHeightFactor=_heightSizedToContainerHeightFactor;
@property(nonatomic) float height; // @synthesize height=_height;
@property(nonatomic) _Bool heightSizedToContainerHeight; // @synthesize heightSizedToContainerHeight=_heightSizedToContainerHeight;
@property(nonatomic) _Bool heightSizedToContentHeight; // @synthesize heightSizedToContentHeight=_heightSizedToContentHeight;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_resetWidth;
- (void)widthSizedToContainerWidthFactor:(float)arg1;
- (void)_resetHeight;
- (void)heightSizedToContainerWidthFactor:(float)arg1;
@property(nonatomic) struct CGSize size;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

