//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ChatKit/CKAnimatedImageMediaObject.h>

@interface CKAnimatedEmojiMediaObject : CKAnimatedImageMediaObject
{
}

+ (_Bool)shouldShadePreview;
+ (_Bool)shouldScaleUpPreview;
+ (id)attachmentSummary:(unsigned long long)arg1;
+ (id)UTITypes;
- (id)previewForWidth:(double)arg1 orientation:(BOOL)arg2;
- (Class)previewBalloonViewClass;
- (id)icon;
- (id)backgroundColorOverride;
- (id)previewItemTitle;
- (id)pasteboardItem;

@end

