//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class CKLabel, NSMutableArray, UIImageView;

@interface CKAvatarTitleCollectionReusableView : UICollectionReusableView
{
    _Bool _avatarPickerActive;
    long long _style;
    long long _avatarTitleAccessoryImageType;
    long long _statusIndicatorType;
    CKLabel *_titleLabel;
    UIImageView *_chevronImageView;
    UIImageView *_statusIndicatorImageView;
    NSMutableArray *_pendingTitles;
}

+ (id)supplementaryViewKind;
+ (id)reuseIdentifier;
@property(retain, nonatomic) NSMutableArray *pendingTitles; // @synthesize pendingTitles=_pendingTitles;
@property(retain, nonatomic) UIImageView *statusIndicatorImageView; // @synthesize statusIndicatorImageView=_statusIndicatorImageView;
@property(retain, nonatomic) UIImageView *chevronImageView; // @synthesize chevronImageView=_chevronImageView;
@property(retain, nonatomic) CKLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) long long statusIndicatorType; // @synthesize statusIndicatorType=_statusIndicatorType;
@property(nonatomic, getter=isAvatarPickerActive) _Bool avatarPickerActive; // @synthesize avatarPickerActive=_avatarPickerActive;
@property(nonatomic) long long avatarTitleAccessoryImageType; // @synthesize avatarTitleAccessoryImageType=_avatarTitleAccessoryImageType;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (_Bool)isLTR;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)configureWithTitle:(id)arg1;
- (void)_animateFromQueue;
- (void)setTitle:(id)arg1 animated:(_Bool)arg2;
- (void)_rotateChevronImageView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

