//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ChatKit/CKUIBehaviorPad.h>

@interface CKUIBehaviorHUDPad : CKUIBehaviorPad
{
}

- (struct UIEdgeInsets)entryViewHorizontalCoverInsets;
- (struct UIEdgeInsets)entryViewVerticalCoverInsets;
- (_Bool)usesActionMenu;
- (_Bool)entryFieldShouldUseBackdropView;
- (_Bool)joystickUsesWindow;
- (id)theme;

@end

