//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthKit/HKCorrelation.h>

@interface HKCorrelation (HKDataMetadataDetailSection)
- (void)_hk_bloodPressureDetailRowForSampleType:(id)arg1 title:(id)arg2 section:(id)arg3;
- (void)_hk_bloodPressureDetailRowsWithSection:(id)arg1;
- (void)addDetailValuesToSection:(id)arg1;
@end

