//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@interface UIBarButtonItem (HealthUI)
+ (id)hk_sequencingButtonWithTitle:(id)arg1 accessibilityFormatString:(id)arg2;
+ (id)hk_backButtonForDate:(id)arg1;
+ (id)hk_backButtonWithTitle:(id)arg1;
@end

