//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NDAnalyticsEnvelopeTracker.h"

@class NSString;

@interface NSSNewsAnalyticsEnvelopeTrackerProxy : NSObject <NDAnalyticsEnvelopeTracker>
{
}

- (void)registerEnvelopeContentTypesAsDropped:(id)arg1 forReason:(unsigned long long)arg2 withError:(id)arg3;
- (void)registerEnvelopeContentTypesAsUploaded:(id)arg1;
- (void)registerEnvelopeContentTypesAsRetainedForUploadRetry:(id)arg1;
- (void)registerEnvelopeContentTypesAsPreparedForUpload:(id)arg1;
- (void)registerEnvelopesAsReceivedByUploader:(id)arg1;
- (void)registerEnvelopesAsSubmittedToUploader:(id)arg1;
- (void)registerEnvelopesAsCreated:(id)arg1;
- (void)registerEnvelopeCreationAnticipatedForContentType:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

