//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <SpringBoard/BSDescriptionProviding-Protocol.h>
#import <SpringBoard/SBAssistantObserver-Protocol.h>
#import <SpringBoard/SBFloatingDockRootViewControllerDelegate-Protocol.h>
#import <SpringBoard/SBFolderPresentationObserver-Protocol.h>
#import <SpringBoard/SBIconLocationPresenting-Protocol.h>
#import <SpringBoard/SBIconViewProviding-Protocol.h>
#import <SpringBoard/SBIconViewQuerying-Protocol.h>
#import <SpringBoard/SBLayoutStateTransitionObserver-Protocol.h>
#import <SpringBoard/SBReusableViewMapDelegate-Protocol.h>
#import <SpringBoard/SBRootFolderPageStateObserver-Protocol.h>
#import <SpringBoard/SBSystemGestureRecognizerDelegate-Protocol.h>

@class NSPointerArray, NSSet, NSString, PTToggleTestRecipe, SBApplication, SBDeviceOrientationUpdateDeferralAssertion, SBFAnalyticsClient, SBFailingSystemGestureRecognizer, SBFloatingDockBehaviorAssertion, SBFloatingDockRootViewController, SBFloatingDockViewController, SBFolderController, SBIconController, SBIconListView, SBLayoutStateTransitionCoordinator, SBMainScreenActiveInterfaceOrientationWindow, SBReusableViewMap, UIViewController, _UILegibilitySettings;
@protocol BSInvalidatable, SBFloatingDockControllerDelegate;

@interface SBFloatingDockController : NSObject <SBFloatingDockRootViewControllerDelegate, SBFolderPresentationObserver, SBSystemGestureRecognizerDelegate, SBRootFolderPageStateObserver, SBAssistantObserver, BSDescriptionProviding, SBReusableViewMapDelegate, SBLayoutStateTransitionObserver, SBIconViewQuerying, SBIconLocationPresenting, SBIconViewProviding>
{
    SBFloatingDockRootViewController *_viewController;
    _Bool _homeScreenTransitioningToTodayView;
    _Bool _homeScreenTodayViewTransitioning;
    NSPointerArray *_floatingDockBehaviorAssertionsByLevel[12];
    NSPointerArray *_floatingDockWindowLevelAssertionsByPriority[5];
    SBFAnalyticsClient *_analyticsClient;
    SBFloatingDockBehaviorAssertion *_inAppFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_todayViewFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_iconPullSearchGestureShowingFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_openFolderOverHomeScreenFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_openFolderOverSceneLayoutFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_activeGestureFloatingDockBehaviorAssertion;
    SBFloatingDockBehaviorAssertion *_assistantFloatingDockBehaviorAssertion;
    SBDeviceOrientationUpdateDeferralAssertion *_deferOrientationUpdatesAssertion;
    SBReusableViewMap *_iconViewMap;
    id <BSInvalidatable> _floatingDockStateDumpHandle;
    PTToggleTestRecipe *_testRecipe;
    SBMainScreenActiveInterfaceOrientationWindow *_floatingDockWindow;
    id <SBFloatingDockControllerDelegate> _delegate;
    SBFailingSystemGestureRecognizer *_dismissFloatingDockSystemGestureRecognizer;
    SBIconController *_iconController;
    SBFloatingDockBehaviorAssertion *_activeAssertion;
    SBLayoutStateTransitionCoordinator *_transitionCoordinator;
}

+ (_Bool)isFloatingDockSupported;
@property(nonatomic) __weak SBLayoutStateTransitionCoordinator *transitionCoordinator; // @synthesize transitionCoordinator=_transitionCoordinator;
@property(nonatomic) __weak SBFloatingDockBehaviorAssertion *activeAssertion; // @synthesize activeAssertion=_activeAssertion;
@property(readonly, nonatomic) SBIconController *iconController; // @synthesize iconController=_iconController;
@property(readonly, nonatomic) SBFailingSystemGestureRecognizer *dismissFloatingDockSystemGestureRecognizer; // @synthesize dismissFloatingDockSystemGestureRecognizer=_dismissFloatingDockSystemGestureRecognizer;
@property(readonly, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) __weak id <SBFloatingDockControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SBMainScreenActiveInterfaceOrientationWindow *floatingDockWindow; // @synthesize floatingDockWindow=_floatingDockWindow;
- (void).cxx_destruct;
- (void)_setupStateDumper;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (void)assistantDidDisappear:(id)arg1;
- (void)assistantWillAppear:(id)arg1;
- (void)_recalculateWindowLevelForWindowLevelAssertions;
- (void)rootFolderPageStateProvider:(id)arg1 didEndTransitionFromState:(long long)arg2 toState:(long long)arg3 successfully:(_Bool)arg4;
- (void)rootFolderPageStateProvider:(id)arg1 willEndTransitionToState:(long long)arg2 successfully:(_Bool)arg3;
- (void)rootFolderPageStateProvider:(id)arg1 didContinueTransitionToState:(long long)arg2 progress:(double)arg3;
- (void)rootFolderPageStateProvider:(id)arg1 willBeginTransitionToState:(long long)arg2 animated:(_Bool)arg3 interactive:(_Bool)arg4;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidBeginWithTransitionContext:(id)arg2;
- (void)_gestureRecognizerFailed:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)viewForSystemGestureRecognizer:(id)arg1;
- (void)_configureFloatingDockBehaviorAssertionForOpenFolder:(id)arg1 atLevel:(unsigned long long)arg2;
- (void)_handleTransitionForFolder:(id)arg1 atLevel:(unsigned long long)arg2 presenting:(_Bool)arg3 withTransitionCoordinator:(id)arg4;
- (void)iconManager:(id)arg1 willPerformTransitionWithFolder:(id)arg2 presenting:(_Bool)arg3 withTransitionCoordinator:(id)arg4;
- (_Bool)viewMap:(id)arg1 shouldRecycleView:(id)arg2;
- (id)recycledViewsContainerProviderForViewMap:(id)arg1;
- (unsigned long long)viewMap:(id)arg1 maxRecycledViewsOfClass:(Class)arg2;
- (void)configureIconView:(id)arg1 forIcon:(id)arg2;
- (_Bool)isIconViewRecycled:(id)arg1;
- (void)recycleIconView:(id)arg1;
- (id)dequeueReusableIconViewOfClass:(Class)arg1;
- (id)iconViewMap;
- (double)minimumHomeScreenScaleForFloatingDockRootViewController:(id)arg1;
- (void)floatingDockRootViewControllerDidEndPresentationTransition:(id)arg1;
- (void)floatingDockRootViewController:(id)arg1 willPerformTransitionWithFolder:(id)arg2 presenting:(_Bool)arg3 withTransitionCoordinator:(id)arg4;
- (void)floatingDockRootViewController:(id)arg1 modifyProgress:(double)arg2 interactive:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)floatingDockRootViewController:(id)arg1 floatingDockWantsToBePresented:(_Bool)arg2;
- (void)floatingDockRootViewController:(id)arg1 willChangeToHeight:(double)arg2;
- (_Bool)floatingDockRootViewControllerShouldHandlePanGestureRecognizer:(id)arg1;
- (_Bool)_allowGestureRecognizers;
- (_Bool)_canPresentFloatingDock;
- (void)_dismissFloatingDockIfPresentedAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_presentFloatingDockIfDismissedAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_handleSystemGestureRecognizer:(id)arg1;
- (void)registerAsSharedInstance;
- (void)_evaluateAssertions:(unsigned long long)arg1 interactive:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)_deriveActiveAssertion:(id *)arg1 dockProgress:(double *)arg2;
- (unsigned long long)_indexOfPointerArray:(id)arg1 ofObject:(void *)arg2;
- (void)_updateFloatingDockBehaviorAssertionsInteractive:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_removeFloatingDockBehaviorAssertion:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_addFloatingDockBehaviorAssertion:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)_clearGestureAssertion;
- (void)_removeFloatingDockWindowLevelAssertion:(id)arg1;
- (void)_addFloatingDockWindowLevelAssertion:(id)arg1;
- (_Bool)handlePromptingUserToUninstallIcon:(id)arg1 location:(id)arg2;
- (_Bool)shouldShowCloseBoxForIconView:(id)arg1 proposedValue:(_Bool)arg2;
- (void)layoutUserControlledIconLists:(double)arg1 animationType:(long long)arg2 forceRelayout:(_Bool)arg3;
- (void)dismissPresentedFolderAnimated:(_Bool)arg1 withTransitionContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissPresentedFolderAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentFolderForIcon:(id)arg1 location:(id)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
@property(readonly, copy, nonatomic) NSSet *presentedIconLocations;
- (_Bool)isPresentingIconLocation:(id)arg1;
- (void)enumerateDisplayedIconViewsForIcon:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateDisplayedIconViewsUsingBlock:(CDUnknownBlockType)arg1;
- (_Bool)isDisplayingIcon:(id)arg1;
- (_Bool)isDisplayingIconView:(id)arg1 inLocation:(id)arg2;
- (_Bool)isDisplayingIconView:(id)arg1;
- (_Bool)isDisplayingIcon:(id)arg1 inLocations:(id)arg2;
- (_Bool)isDisplayingIcon:(id)arg1 inLocation:(id)arg2;
- (id)firstIconViewForIcon:(id)arg1 excludingLocations:(id)arg2;
- (id)firstIconViewForIcon:(id)arg1;
- (id)firstIconViewForIcon:(id)arg1 inLocations:(id)arg2;
- (id)iconViewForIcon:(id)arg1 location:(id)arg2;
- (void)dismissFloatingDockIfPresentedAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)presentFloatingDockIfDismissedAnimated:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) SBApplication *requestedSuggestedApplication;
@property(readonly, nonatomic) SBFloatingDockViewController *floatingDockViewController;
@property(readonly, nonatomic) SBIconListView *suggestionsIconListView;
@property(readonly, nonatomic) SBIconListView *userIconListView;
@property(readonly, nonatomic) SBFolderController *presentedFolderController;
@property(readonly, nonatomic, getter=isPresentingFolder) _Bool presentingFolder;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, nonatomic) struct CGRect floatingDockScreenPresentationFrame;
@property(readonly, nonatomic) struct CGRect floatingDockScreenFrame;
@property(readonly, nonatomic) double translationFromFullyPresentedFrame;
@property(readonly, nonatomic) double floatingDockViewTopMargin;
@property(readonly, nonatomic) double preferredVerticalMargin;
@property(readonly, nonatomic) double effectiveFloatingDockHeight;
@property(readonly, nonatomic) double floatingDockHeight;
@property(readonly, nonatomic) double maximumDockContinuousCornerRadius;
@property(readonly, nonatomic) double maximumFloatingDockHeight;
@property(readonly, nonatomic, getter=isGesturePossible) _Bool gesturePossible;
@property(readonly, nonatomic, getter=isFloatingDockFullyPresented) _Bool floatingDockFullyPresented;
@property(readonly, nonatomic, getter=isFloatingDockPresented) _Bool floatingDockPresented;
- (void)dealloc;
- (id)init;
- (id)initWithAnalyticsClient:(id)arg1;
- (id)initWithIconController:(id)arg1;
- (id)initWithIconController:(id)arg1 analyticsClient:(id)arg2;
- (id)initWithIconController:(id)arg1 applicationController:(id)arg2 recentsController:(id)arg3 recentsDataStore:(id)arg4 transitionCoordinator:(id)arg5 appSuggestionManager:(id)arg6 analyticsClient:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

