//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, SBCPlaybackPositionDomain, SBCPlaybackPositionValueService;

@interface VideosExtrasBookmarkController : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    SBCPlaybackPositionDomain *_domain;
    SBCPlaybackPositionValueService *_extrasService;
    NSMutableDictionary *_entities;
    NSMutableDictionary *_updateTimeForEntities;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_ubiquitousIdentifierForAsset:(id)arg1;
- (void)_loadAllBookmarksWithRemainingAssets:(id)arg1 bookmarkTimes:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (_Bool)pushBookmarkForAsset:(id)arg1 bookmarkTime:(double)arg2 playedToNominalLength:(_Bool)arg3;
- (void)pullBookmarksForAssets:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

