//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class VideosExtrasCarouselViewController;

@protocol VideosExtrasCarouselViewControllerDataSource
- (unsigned long long)carouselSize;
- (void)carouselViewController:(VideosExtrasCarouselViewController *)arg1 configureCarouselCollectionViewCell:(id <VideosExtrasCarouselCollectionViewCell>)arg2 forItemAtIndex:(unsigned long long)arg3 withThumbnailImageContainerSize:(struct CGSize)arg4;
- (unsigned long long)numberOfItemsInCarouselViewController:(VideosExtrasCarouselViewController *)arg1;
@end

