//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HeadBoardUI/_UISceneBSActionHandler-Protocol.h>
#import <HeadBoardUI/_UISceneComponentProviding-Protocol.h>

@class BSTransaction, NSString, UIScene;

@interface HBUILaunchAnimator : NSObject <_UISceneBSActionHandler, _UISceneComponentProviding>
{
    UIScene *_scene;
    BSTransaction *_animationTransaction;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BSTransaction *animationTransaction; // @synthesize animationTransaction=_animationTransaction;
@property(nonatomic, getter=_scene, setter=_setScene:) __weak UIScene *_scene; // @synthesize _scene;
- (id)_respondToActions:(id)arg1 forFBSScene:(id)arg2 inUIScene:(id)arg3 fromTransitionContext:(id)arg4;
- (id)_actionHandlersForScene:(id)arg1;
- (void)_failAnimationWithAction:(id)arg1;
- (void)_performLaunchAnimationWithAction:(id)arg1;
- (void)_prepareForScreenSaverAnimationWithAction:(id)arg1;
- (void)_prepareForApplicationAnimationWithAction:(id)arg1;
- (id)_snapshotRootAnimationEnvironment;
- (id)_rootAnimationEnvironment;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating;
- (void)dealloc;
- (id)initWithScene:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

