//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSLayoutConstraint;

@interface INKMultilineButton : UIButton
{
    NSLayoutConstraint *_labelWidthConstraint;
    NSLayoutConstraint *_labelTopConstraint;
    NSLayoutConstraint *_labelBottomConstraint;
    _Bool _needToInvalidateTitleLableIntrinsicContentSize;
    NSLayoutConstraint *_fm_workaround_height_constraint;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool needToInvalidateTitleLableIntrinsicContentSize; // @synthesize needToInvalidateTitleLableIntrinsicContentSize=_needToInvalidateTitleLableIntrinsicContentSize;
@property(retain, nonatomic) NSLayoutConstraint *fm_workaround_height_constraint; // @synthesize fm_workaround_height_constraint=_fm_workaround_height_constraint;
- (void)setContentEdgeInsets:(struct UIEdgeInsets)arg1;
- (void)updateConstraints;
- (void)traitCollectionDidChange:(id)arg1;

@end

