//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotoLibraryServices/PLJournalEntryPayload.h>

@class NSData, NSDate, NSNumber, NSString;

@interface PLGenericAlbumJournalEntryPayload : PLJournalEntryPayload
{
}

+ (id)nonPersistedModelPropertiesDescription;
+ (id)modelPropertiesDescription;
- (_Bool)comparePayloadValue:(id)arg1 toObjectDictionaryValue:(id)arg2 forPayloadProperty:(id)arg3;
@property(readonly, nonatomic) NSDate *creationDate;
@property(retain, nonatomic) NSData *userQueryData;
@property(readonly, nonatomic) NSString *importSessionID;
@property(readonly, nonatomic) NSString *customKeyAssetUUID;
@property(readonly, nonatomic) int customSortKey;
@property(readonly, nonatomic) _Bool customSortAscending;
@property(readonly, nonatomic) _Bool isInTrash;
@property(readonly, nonatomic) _Bool isPinned;
@property(readonly, nonatomic) NSNumber *kind;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) NSString *cloudGUID;
- (void)updateAlbum:(id)arg1 includePendingChanges:(_Bool)arg2;
- (id)insertAlbumFromDataInManagedObjectContext:(id)arg1;
- (void)updatePayloadAttributes:(id)arg1 withDecodedAttributes:(id)arg2 forPayloadProperty:(id)arg3;
- (void)updateEncodableAttributes:(id)arg1 fromPayloadAttributes:(id)arg2 forPayloadProperty:(id)arg3;
- (_Bool)updatePayloadAttributes:(id)arg1 withManagedObject:(id)arg2 forPayloadProperty:(id)arg3;

@end

