//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PassKitCore/PKTransitPassProperties.h>

@class NSDecimalNumber, NSString;

@interface PKSuicaPassProperties : PKTransitPassProperties
{
    _Bool _inShinkansenStation;
    _Bool _balanceAllowedForCommute;
    _Bool _lowBalanceGateNotificationEnabled;
    _Bool _greenCarTicketUsed;
}

+ (id)passPropertiesForPass:(id)arg1;
@property(readonly, nonatomic, getter=isGreenCarTicketUsed) _Bool greenCarTicketUsed; // @synthesize greenCarTicketUsed=_greenCarTicketUsed;
@property(readonly, nonatomic, getter=isLowBalanceGateNotificationEnabled) _Bool lowBalanceGateNotificationEnabled; // @synthesize lowBalanceGateNotificationEnabled=_lowBalanceGateNotificationEnabled;
@property(readonly, nonatomic, getter=isBalanceAllowedForCommute) _Bool balanceAllowedForCommute; // @synthesize balanceAllowedForCommute=_balanceAllowedForCommute;
@property(readonly, nonatomic, getter=isInShinkansenStation) _Bool inShinkansenStation; // @synthesize inShinkansenStation=_inShinkansenStation;
- (id)_initWithProperties:(id)arg1;

// Remaining properties
@property(readonly, nonatomic, getter=isBlacklisted) _Bool blacklisted; // @dynamic blacklisted;
@property(readonly, nonatomic, getter=isInStation) _Bool inStation; // @dynamic inStation;
@property(readonly, copy, nonatomic) NSDecimalNumber *transitBalance; // @dynamic transitBalance;
@property(readonly, copy, nonatomic) NSString *transitBalanceCurrencyCode; // @dynamic transitBalanceCurrencyCode;

@end

