//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSString, NSURL;

@interface _LSStringLocalizer : NSObject
{
    NSURL *_url;
    _Bool _isMainBundle;
    NSString *_stringsFile;
    NSMutableDictionary *_stringsFileContent;
    NSMutableDictionary *_unlocalizedInfoPlistStrings;
    NSArray *_bundleLocalizations;
}

+ (id)coreTypesLocalizer;
+ (id)frameworkBundleLocalizer;
+ (void)setPreferredLocalizationsForXCTests:(id)arg1;
+ (id)preferredLocalizationsForXCTests;
+ (id)queue;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)localizedStringDictionaryWithString:(id)arg1 defaultValue:(id)arg2;
- (id)localizedStringsWithStrings:(id)arg1 preferredLocalizations:(id)arg2;
- (id)localizedStringWithString:(id)arg1 preferredLocalizations:(id)arg2;
- (void)dealloc;
- (id)initWithBundleURL:(id)arg1 stringsFile:(id)arg2;
- (id)init;
-     // Error parsing type: @28@0:8^{LSDatabase={__CFRuntimeBase=QAQ}^{LSDBImpl}^{__CSStore}{LSSchema=I{?={CSMap=I{CSMapCallbacks=^?^?^?^?^?^?}^{CSMapContext}{os_unfair_lock_s=I}I^{_CSMapHeader}^I^I}I}{?=II}IIII{?={CSMap=I{CSMapCallbacks=^?^?^?^?^?^?}^{CSMapContext}{os_unfair_lock_s=I}I^{_CSMapHeader}^I^I}}[12{?={CSMap=I{CSMapCallbacks=^?^?^?^?^?^?}^{CSMapContext}{os_unfair_lock_s=I}I^{_CSMapHeader}^I^I}^{?}^{?}IC}]IIIIIII^{_LSSchemaCache}}}16I24, name: initWithDatabase:pluginUnit:
-     // Error parsing type: @32@0:8^{LSDatabase={__CFRuntimeBase=QAQ}^{LSDBImpl}^{__CSStore}{LSSchema=I{?={CSMap=I{CSMapCallbacks=^?^?^?^?^?^?}^{CSMapContext}{os_unfair_lock_s=I}I^{_CSMapHeader}^I^I}I}{?=II}IIII{?={CSMap=I{CSMapCallbacks=^?^?^?^?^?^?}^{CSMapContext}{os_unfair_lock_s=I}I^{_CSMapHeader}^I^I}}[12{?={CSMap=I{CSMapCallbacks=^?^?^?^?^?^?}^{CSMapContext}{os_unfair_lock_s=I}I^{_CSMapHeader}^I^I}^{?}^{?}IC}]IIIIIII^{_LSSchemaCache}}}16I24I28, name: initWithDatabase:bundleUnit:delegate:
- (id)localizedStringWithString:(id)arg1 inBundle:(struct __CFBundle *)arg2 localeCode:(id)arg3 keep:(_Bool)arg4;
- (id)localizedStringWithString:(id)arg1 inBundle:(struct __CFBundle *)arg2 preferredLocalizations:(id)arg3 keep:(_Bool)arg4;
- (id)stringsFileContentInBundle:(struct __CFBundle *)arg1 withLocaleCode:(id)arg2 keep:(_Bool)arg3;
- (struct __CFBundle *)bundle;
- (id)_initWithBundleURL:(id)arg1 stringsFile:(id)arg2 keepBundle:(_Bool)arg3;

@end

