//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FCHeadlineMetadata.h"

@class NSDate, NSDictionary, NSString;

@interface FCArticleMetadata : NSObject <FCHeadlineMetadata>
{
    NSDictionary *_dictionary;
    NSDate *_displayDate;
}

@property(retain, nonatomic) NSDate *displayDate; // @synthesize displayDate=_displayDate;
@property(retain, nonatomic) NSDictionary *dictionary; // @synthesize dictionary=_dictionary;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) _Bool isTreatedAsNew;
@property(readonly, nonatomic) NSString *articleID;
@property(readonly, nonatomic) NSString *storyType;
- (id)initWithDictionary:(id)arg1;

@end

