//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FACATransitionObserver : NSObject
{
    NSString *_stateName;
    CDUnknownBlockType _completion;
}

@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) NSString *stateName; // @synthesize stateName=_stateName;
- (void).cxx_destruct;
- (id)initWithStateName:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

