//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IBCocoaTouchToolFoundation/IBBinaryArchiving-Protocol.h>

@class IBCustomViewDrawingDescription, NSString;

@interface IBPlaceholderDrawingAttributes : NSObject <IBBinaryArchiving>
{
    _Bool _drawTopEdgeShadow;
    NSString *_title;
    NSString *_subtitle;
    NSString *_explanatoryText;
    long long _style;
    IBCustomViewDrawingDescription *_customViewDrawingDescription;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool drawTopEdgeShadow; // @synthesize drawTopEdgeShadow=_drawTopEdgeShadow;
@property(retain, nonatomic) IBCustomViewDrawingDescription *customViewDrawingDescription; // @synthesize customViewDrawingDescription=_customViewDrawingDescription;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *explanatoryText; // @synthesize explanatoryText=_explanatoryText;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

