//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AvatarUI/AVTAvatarAttributeEditorLayout.h>

@interface AVTAvatarAttributeEditorTransitionFromActionsStartingLandscapeRightLayout : AVTAvatarAttributeEditorLayout
{
    struct CGRect _avatarContainerFrame;
}

- (struct CGRect)avatarContainerFrame;
- (struct UIEdgeInsets)attributesContentViewScrollIndicatorInsets;
- (struct UIEdgeInsets)attributesContentViewInsets;
- (struct CGRect)verticalRuleFrame;
- (double)verticalRuleAlpha;
- (struct CGRect)headerMaskingViewFrame;
- (double)headerMaskingViewAlpha;
- (struct CGRect)userInfoFrame;
- (struct CGRect)attributesContentViewFrame;
- (struct CGRect)groupDialContainerFrame;
- (double)leftSideWidth;
- (double)leftSideOriginX;
- (double)rightSideWidth;
- (double)rightSideOriginX;
- (unsigned long long)supportedLayoutOrientation;
- (id)initWithContainerSize:(struct CGSize)arg1 insets:(struct UIEdgeInsets)arg2 screenScale:(double)arg3 avatarViewContainerFrame:(struct CGRect)arg4;

@end

