//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AVHapticParameterCurveValue : NSObject
{
    float _value;
    double _time;
}

@property float value; // @synthesize value=_value;
@property double time; // @synthesize time=_time;

@end

