//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AXMPhotoVisionSupport : NSObject
{
}

+ (id)localizedLabelForClassificationObservation:(id)arg1;
+ (id)processSceneClassifications:(id)arg1 withOptions:(unsigned int)arg2;
+ (id)nonLeafNodeLabels;
+ (id)leafNodeLabels;
+ (id)buildGraphStatisticsDescription;
+ (id)buildParentChainDescriptionForAllNodes;
+ (id)buildTaxonomyDescription;

@end

