//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, WFLocation;

@protocol NWKForecastServable
- (void)setForecastTypesInterestMask:(unsigned int)arg1;
- (void)invalidate;
- (void)setupSnapshotForLocations:(NSArray *)arg1 onlyObserveInForegroundOnly:(_Bool)arg2;
- (void)setLocationForUpdates:(WFLocation *)arg1 lastUpdate:(unsigned int)arg2 onlyObserveInForegroundOnly:(_Bool)arg3;
- (void)setLocationForCachedUpdates:(WFLocation *)arg1 lastUpdate:(unsigned int)arg2;
@end

