//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class CAFilter;

@interface ASAuthorizationAppleIDButton : UIControl
{
    int _type;
    int _style;
    CAFilter *_highlightFilter;
    float _cornerRadius;
}

+ (Class)layerClass;
+ (float)defaultCornerRadius;
+ (id)buttonWithType:(int)arg1 style:(int)arg2;
- (void).cxx_destruct;
@property(nonatomic) float cornerRadius; // @synthesize cornerRadius=_cornerRadius;
- (id)accessibilityLabel;
- (unsigned long long)accessibilityTraits;
- (_Bool)isAccessibilityElement;
- (int)_ak_buttonStyle;
- (int)_ak_buttonType;
- (void)setHighlighted:(_Bool)arg1;
- (void)_performAnimationToSetHighlighted:(_Bool)arg1;
- (void)_createHighlightFilterIfNecessary;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)_drawRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithAuthorizationButtonType:(int)arg1 authorizationButtonStyle:(int)arg2;

@end

