//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__COSPasskeyEntryViewControllerAccessibility_super.h"

@interface COSPasskeyEntryViewControllerAccessibility : __COSPasskeyEntryViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)textDidChange:(id)arg1;
- (id)init;
- (void)_accessibilityLoadAccessibilityInformation;

@end

