//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KNHLController : NSObject
{
}

+ (_Bool)isExternalHyperlinkURL:(id)arg1;
+ (id)smartFieldForRep:(id)arg1 atUnscaledPoint:(struct CGPoint)arg2 outRep:(id *)arg3;
+ (long long)hyperlinkTypeFromHyperlinkURL:(id)arg1;
+ (_Bool)URLContainsKeynoteSpecificHyperlink:(id)arg1;
+ (id)uniqueIdentifierFromHyperlinkURL:(id)arg1;

@end

