//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class PBUnknownFields;

@interface GEOCommonOptions : PBCodable <NSCopying>
{
    PBUnknownFields *_unknownFields;
    _Bool _excludeGuidance;
    _Bool _includeSnapScoreMetadataDebug;
    _Bool _includeSummaryForPredictedDestination;
    _Bool _includeTravelTimeAggressive;
    _Bool _includeTravelTimeConservative;
    _Bool _includeTravelTimeEstimate;
    struct {
        unsigned int has_excludeGuidance:1;
        unsigned int has_includeSnapScoreMetadataDebug:1;
        unsigned int has_includeSummaryForPredictedDestination:1;
        unsigned int has_includeTravelTimeAggressive:1;
        unsigned int has_includeTravelTimeConservative:1;
        unsigned int has_includeTravelTimeEstimate:1;
    } _flags;
}

+ (_Bool)isValid:(id)arg1;
- (void).cxx_destruct;
- (void)clearUnknownFields:(_Bool)arg1;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (void)readAll:(_Bool)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasIncludeSnapScoreMetadataDebug;
@property(nonatomic) _Bool includeSnapScoreMetadataDebug;
@property(nonatomic) _Bool hasIncludeSummaryForPredictedDestination;
@property(nonatomic) _Bool includeSummaryForPredictedDestination;
@property(nonatomic) _Bool hasExcludeGuidance;
@property(nonatomic) _Bool excludeGuidance;
@property(nonatomic) _Bool hasIncludeTravelTimeConservative;
@property(nonatomic) _Bool includeTravelTimeConservative;
@property(nonatomic) _Bool hasIncludeTravelTimeEstimate;
@property(nonatomic) _Bool includeTravelTimeEstimate;
@property(nonatomic) _Bool hasIncludeTravelTimeAggressive;
@property(nonatomic) _Bool includeTravelTimeAggressive;

@end

