//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DataAccess/DAMailboxRequest.h>

@class DAMailMessage;

@interface DADraftMessageRequest : DAMailboxRequest
{
    _Bool _send;
    DAMailMessage *_message;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool send; // @synthesize send=_send;
@property(retain, nonatomic) DAMailMessage *message; // @synthesize message=_message;
- (id)description;
- (id)initWithRequestType:(int)arg1 message:(id)arg2 send:(_Bool)arg3;

@end

