//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController<CRKCardViewControlling>;

@protocol CRKCardPresentationDelegate <NSObject>

@optional
@property(readonly, nonatomic) id <CRKCardViewControllerDelegate> cardViewControllerDelegate;
- (void)cardPresentation:(id <CRKCardPresenting>)arg1 willTransitionFromCardViewController:(UIViewController<CRKCardViewControlling> *)arg2 toCardViewController:(UIViewController<CRKCardViewControlling> *)arg3 withAnimationCoordinator:(id <CRKAnimationCoordinating>)arg4;
- (long long)semanticContentAttributeForCardPresentation:(id <CRKCardPresenting>)arg1;
- (long long)cardPresentation:(id <CRKCardPresenting>)arg1 compareCardSectionViewProviderOne:(id <CRKIdentifiedCardSectionViewProviding>)arg2 providerTwo:(id <CRKIdentifiedCardSectionViewProviding>)arg3;
- (long long)cardPresentation:(id <CRKCardPresenting>)arg1 compareCardViewControllerProviderOne:(id <CRKIdentifiedProviding>)arg2 providerTwo:(id <CRKIdentifiedProviding>)arg3;
@end

