//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSXPCConnection;

@interface USUsageReporter : NSObject
{
    NSXPCConnection *_xpcConnection;
}

+ (void)synchronizeUsageWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (id)getLocalDeviceIdentifierAndReturnError:(id *)arg1;
- (void).cxx_destruct;
@property(readonly) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
- (void)fetchReportsDuringInterval:(id)arg1 partitionInterval:(double)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)fetchReportsDuringInterval:(id)arg1 partitionInterval:(double)arg2 forceImmediateSync:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)getLocalDeviceIdentifierAndReturnError:(id *)arg1;
- (void)dealloc;
- (id)init;

@end

