//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface PXAssetVariationOption : NSObject <NSCopying>
{
    _Bool _recommended;
    _Bool _current;
    long long _variationType;
    NSString *_localizedName;
}

+ (id)_localizedNameForVariationType:(long long)arg1;
+ (id)variationOptionWithType:(long long)arg1 recommended:(_Bool)arg2 current:(_Bool)arg3;
@property(readonly, nonatomic, getter=isCurrent) _Bool current; // @synthesize current=_current;
@property(readonly, nonatomic, getter=isRecommended) _Bool recommended; // @synthesize recommended=_recommended;
@property(readonly, copy, nonatomic) NSString *localizedName; // @synthesize localizedName=_localizedName;
@property(readonly, nonatomic) long long variationType; // @synthesize variationType=_variationType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (_Bool)isEqualToVariationOption:(id)arg1;
- (_Bool)isEqual:(id)arg1;

@end

