//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class PXCloudQuotaController, UIView;

@protocol PXCloudQuotaControllerDelegate <NSObject>
- (struct NSObject *)presentingViewControllerForCloudQuotaController:(PXCloudQuotaController *)arg1;
- (void)cloudQuotaController:(PXCloudQuotaController *)arg1 presentInformationBanner:(UIView *)arg2;
@end

