//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

#import <PhotosUICore/PXGReusableView-Protocol.h>

@class PXCuratedLibraryOverlayButtonConfiguration, UIImageView, UILabel, UIView, UIVisualEffectView;

@interface PXCuratedLibraryOverlayButton : UIControl <PXGReusableView>
{
    PXCuratedLibraryOverlayButtonConfiguration *_userData;
    UIVisualEffectView *_effectView;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UIView *_separatorLine;
    struct CGRect _clippingRect;
}

+ (void)_getSize:(out struct CGSize *)arg1 titleFrame:(out struct CGRect *)arg2 iconFrame:(out struct CGRect *)arg3 separatorLineFrame:(out struct CGRect *)arg4 forConfiguration:(id)arg5 title:(id)arg6;
+ (struct CGSize)sizeWithConfiguration:(id)arg1;
+ (struct CGSize)_sizeOfTitle:(id)arg1 withFont:(struct UIFont *)arg2;
+ (id)buttonSizeCache;
+ (id)titleSizeCache;
@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(nonatomic) struct CGRect clippingRect; // @synthesize clippingRect=_clippingRect;
@property(copy, nonatomic) PXCuratedLibraryOverlayButtonConfiguration *userData; // @synthesize userData=_userData;
- (void).cxx_destruct;
- (void)_updateEffectView;
- (void)_updateEffectViewBackgroundStyle;
- (void)_platformSpecificViewSetup;
- (void)_setupEffectView;
- (void)_performAction:(id)arg1;
- (void)_updateButtonWithConfiguration:(id)arg1;
- (void)_setupViews;
- (void)prepareForReuse;
- (void)becomeReusable;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)description;
- (id)initWithFrame:(struct CGRect)arg1;

@end

