//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "__VUICardViewAccessibility_super.h"

@interface VUICardViewAccessibility : __VUICardViewAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityAttributedValue;
- (id)accessibilityLabel;
- (long long)_axCompareStyle:(long long)arg1 toStyle:(long long)arg2;
- (unsigned long long)_accessibilityDownloadState;
- (_Bool)_downloadButtonPressed:(id)arg1;
- (id)accessibilityCustomActions;
- (id)_accessibilityUserTestingChildren;
- (_Bool)isAccessibilityElement;
- (id)_accessibilityEnclosingVUICardCollectionViewCell;

@end

