//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AAUIServerHookDelegate.h"

@class NSArray, NSMutableArray, NSString, RemoteUIController, UIViewController;

@interface AAUIServerUIHookHandler : NSObject <AAUIServerHookDelegate>
{
    NSMutableArray *_hookIdentifiers;
    RemoteUIController *_remoteUIController;
    UIViewController *_presentingControllerOverride;
    NSArray *_serverHooks;
}

@property(copy, nonatomic) NSArray *serverHooks; // @synthesize serverHooks=_serverHooks;
@property(retain, nonatomic) UIViewController *presentingControllerOverride; // @synthesize presentingControllerOverride=_presentingControllerOverride;
- (void).cxx_destruct;
- (id)_refreshRequestWithInfo:(id)arg1 initiatingObjectModel:(id)arg2 attributes:(id)arg3;
- (void)_reloadUIWithInfo:(id)arg1 attributes:(id)arg2 initiatingObjectModel:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)refreshWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_responseDataForResult:(_Bool)arg1 withError:(id)arg2;
- (void)dismissObjectModelsAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)presentationContextForHook:(id)arg1;
- (id)currentPresenter;
- (void)processServerResponse:(id)arg1;
- (void)processObjectModel:(id)arg1 isModal:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)processObjectModel:(id)arg1 isModal:(_Bool)arg2;
- (void)_rebuildServerHookHandlers;
- (id)initWithRemoteUIController:(id)arg1 hooks:(id)arg2;
- (id)initWithRemoteUIController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

