//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface DAFolder : NSObject
{
    _Bool _isDefault;
    _Bool _hasRemoteChanges;
    NSString *_folderName;
    NSString *_folderID;
    NSString *_parentFolderID;
    int _dataclass;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasRemoteChanges; // @synthesize hasRemoteChanges=_hasRemoteChanges;
@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(nonatomic) int dataclass; // @synthesize dataclass=_dataclass;
@property(copy, nonatomic) NSString *parentFolderID; // @synthesize parentFolderID=_parentFolderID;
@property(copy, nonatomic) NSString *folderID; // @synthesize folderID=_folderID;
@property(copy, nonatomic) NSString *folderName; // @synthesize folderName=_folderName;
- (_Bool)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)parentMailboxID;
- (id)mailboxID;

@end

