//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ShareKit/SHKSharePopUpButtonCell.h>

@interface SHKShareNCPopUpButtonCell : SHKSharePopUpButtonCell
{
}

- (id)_textAttributes;
- (id)_indicatorImage;
- (struct CGRect)_indicatorFrameForCellFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;

@end

