//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class AKAuthorizationTTSUContentView, LSApplicationProxy, NSString, NSTimer, UIImage;
@protocol AKAuthorizationTTSUViewControllerDelegate;

@interface AKAuthorizationTTSUViewController : UIViewController
{
    id <AKAuthorizationTTSUViewControllerDelegate> _delegate;
    NSString *_bundleID;
    UIImage *_appIconImage;
    AKAuthorizationTTSUContentView *_contentView;
    NSTimer *_footerTimer;
    LSApplicationProxy *_applicationProxy;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) LSApplicationProxy *applicationProxy; // @synthesize applicationProxy=_applicationProxy;
@property(retain, nonatomic) NSTimer *footerTimer; // @synthesize footerTimer=_footerTimer;
@property(retain, nonatomic) AKAuthorizationTTSUContentView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIImage *appIconImage; // @synthesize appIconImage=_appIconImage;
@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(nonatomic) __weak id <AKAuthorizationTTSUViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_startAuthorizationInProgressAnimation;
- (void)authorizationInProgress;
- (void)userInteractedWithEndorsingDevice;
- (void)_menuPressed:(id)arg1;
@property(readonly, nonatomic) double appIconCornerRadius;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithAppBundleID:(id)arg1;

@end

