//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSData, NSString, NSURL, RMGenericAuthenticationCredential;

@protocol RMXPCService
- (void)fetchConfigurationsWithTypes:(NSArray *)arg1 completionHandler:(void (^)(NSDictionary *, NSError *))arg2;
- (void)sendStatusForSubscriptionsWithIdentifiers:(NSArray *)arg1 toManagementSourceWithIdentifier:(NSString *)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)queryForStatusSubscriptionsWithIdentifiers:(NSArray *)arg1 fromManagementSourceWithIdentifier:(NSString *)arg2 completionHandler:(void (^)(NSDictionary *, NSError *))arg3;
- (void)sendStatusForKeyPaths:(NSArray *)arg1 toManagementSourceWithIdentifier:(NSString *)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)queryForStatusWithKeyPaths:(NSArray *)arg1 fromManagementSourceWithIdentifier:(NSString *)arg2 completionHandler:(void (^)(NSDictionary *, NSError *))arg3;
- (void)sendStatusData:(NSData *)arg1 toManagementSourceWithIdentifier:(NSString *)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)deviceChannelEnrollmentExistsWithCompletionHandler:(void (^)(_Bool, NSError *))arg1;
- (void)syncWithIdentifier:(NSString *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)unenrollWithIdentifier:(NSString *)arg1 completionHandler:(void (^)(_Bool, NSError *))arg2;
- (void)enrollUserChannelWithURI:(NSURL *)arg1 authenticationCredential:(RMGenericAuthenticationCredential *)arg2 withDataSeparation:(_Bool)arg3 passcodeData:(NSData *)arg4 completionHandler:(void (^)(NSString *, NSError *))arg5;
- (void)enrollDeviceChannelWithURI:(NSURL *)arg1 completionHandler:(void (^)(NSString *, NSError *))arg2;
@end

