//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PassKitCore/PKPaymentWebServiceResponse.h>

@class NSData, NSString;

@interface PKTransactionReceiptAuthorizationResponse : PKPaymentWebServiceResponse
{
    NSString *_authorizationToken;
    NSData *_signature;
    NSString *_conversationIdentifier;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *conversationIdentifier; // @synthesize conversationIdentifier=_conversationIdentifier;
@property(readonly, nonatomic) NSData *signature; // @synthesize signature=_signature;
@property(readonly, nonatomic) NSString *authorizationToken; // @synthesize authorizationToken=_authorizationToken;
- (id)initWithData:(id)arg1;

@end

