//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NotesUI/ICUIApplicationShim-Protocol.h>

@class NSString, UIWindow;
@protocol ICUIApplicationShimDelegate;

@interface ICUIApplicationShim : NSObject <ICUIApplicationShim>
{
    id <ICUIApplicationShimDelegate> _delegate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) id <ICUIApplicationShimDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endReceivingRemoteControlEvents;
- (void)beginReceivingRemoteControlEvents;
@property(readonly, nonatomic) UIWindow *keyWindow;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

