//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TTZoomController : NSObject
{
    double _zoomFactor;
    double _checklistZoomFactor;
}

@property(nonatomic) double checklistZoomFactor; // @synthesize checklistZoomFactor=_checklistZoomFactor;
@property(nonatomic) double zoomFactor; // @synthesize zoomFactor=_zoomFactor;
- (id)unzoomFont:(id)arg1;
- (id)zoomFont:(id)arg1;
- (id)reallyZoomAttributedString:(id)arg1 zoomDirection:(_Bool)arg2;
- (id)unzoomAttributedString:(id)arg1;
- (id)zoomAttributedString:(id)arg1;
- (id)reallyZoomAttributes:(id)arg1 zoomDirection:(_Bool)arg2;
- (id)unzoomAttributes:(id)arg1;
- (id)zoomAttributes:(id)arg1;
- (id)reallyZoomFontInAttributes:(id)arg1 zoomDirection:(_Bool)arg2;
- (id)unzoomFontInAttributes:(id)arg1;
- (id)zoomFontInAttributes:(id)arg1;
- (id)init;

@end

