//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Carousel/FBProcessManagerObserver-Protocol.h>
#import <Carousel/FBProcessObserver-Protocol.h>

@class NSString;

@interface CSLAppStatsProcessStateTransitionMonitor : NSObject <FBProcessManagerObserver, FBProcessObserver>
{
    int _settingsChangedNotifyToken;
    _Bool _isEnabled;
}

- (void)_reloadSettings;
- (void)_recordStateTransitionForBundleID:(id)arg1 transitionType:(unsigned int)arg2;
- (_Bool)_isFavoriteApp:(id)arg1;
- (void)process:(id)arg1 stateDidChangeFromState:(id)arg2 toState:(id)arg3;
- (void)processManager:(id)arg1 didRemoveProcess:(id)arg2;
- (void)processManager:(id)arg1 didAddProcess:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

