//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSLBalancedCATransaction : NSObject
{
    unsigned long long _beginMachTime;
    unsigned long long _elapsedMSActive;
    unsigned long long _stateHandler;
    _Bool _shouldGenerateSeed;
    _Bool _hasBegun;
    _Bool _active;
    unsigned int _transactionID;
    unsigned int _generatedSeed;
}

+ (id)beginTransactionWithTransactionID:(unsigned int)arg1 shouldGenerateSeed:(_Bool)arg2;
@property(readonly, nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) unsigned int generatedSeed; // @synthesize generatedSeed=_generatedSeed;
@property(readonly, nonatomic) unsigned int transactionID; // @synthesize transactionID=_transactionID;
- (void)commit;
- (void)begin;
@property(readonly, nonatomic) unsigned long long elapsedMSActive;
- (id)description;
- (void)dealloc;
- (id)initWithTransactionID:(unsigned int)arg1 shouldGenerateSeed:(_Bool)arg2;

@end

