//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CarouselUIServices/CUISAlertViewController.h>

#import <Carousel/CUISAlertAnimatedTransitioning-Protocol.h>
#import <Carousel/PUICActionSheetControllerDelegate-Protocol.h>

@class CSLGenericAlertItem, CUISAlertSheetController, NSArray, NSString;
@protocol CSLGenericAlertViewControllerDelegate;

@interface CSLGenericAlertViewController : CUISAlertViewController <CUISAlertAnimatedTransitioning, PUICActionSheetControllerDelegate>
{
    _Bool _hasBeenActivated;
    _Bool _hasCalledDismiss;
    CSLGenericAlertItem *_alertItem;
    id <CSLGenericAlertViewControllerDelegate> _delegate;
    CUISAlertSheetController *_alertSheetViewController;
    NSArray *_alertActionItems;
}

@property(retain, nonatomic) NSArray *alertActionItems; // @synthesize alertActionItems=_alertActionItems;
@property(nonatomic) _Bool hasCalledDismiss; // @synthesize hasCalledDismiss=_hasCalledDismiss;
@property(nonatomic) _Bool hasBeenActivated; // @synthesize hasBeenActivated=_hasBeenActivated;
@property(retain, nonatomic) CUISAlertSheetController *alertSheetViewController; // @synthesize alertSheetViewController=_alertSheetViewController;
@property(nonatomic) __weak id <CSLGenericAlertViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) CSLGenericAlertItem *alertItem; // @synthesize alertItem=_alertItem;
- (void).cxx_destruct;
- (void)actionContentControllerCancel:(id)arg1;
- (double)alertTransitionDuration:(id)arg1;
- (void)animateAlertTransition:(id)arg1;
- (void)callDidDismissIfNeeded;
- (void)deactivate;
- (void)activate;
- (id)animationControllerForDismissal;
- (id)animationControllerForPresentation;
- (void)executeAction:(id)arg1;
- (id)alertActionAtIndex:(unsigned int)arg1;
- (id)alert;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithAlertItem:(id)arg1 withServiceName:(id)arg2;
- (id)initWithAlertItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

