//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CSLStateMachineState;

@interface CSLStateMachine : NSObject
{
    CSLStateMachineState *_currentState;
}

- (void).cxx_destruct;
- (void)enterState:(id)arg1;
- (id)stateMachineName;
- (id)stateMachineLog;
- (id)description;
- (void)setCurrentState:(id)arg1;
- (id)currentState;

@end

