//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SpringBoardUIServices/_SBUIBiometricOperationAssertion.h>

#import "BSDescriptionProviding.h"

@class NSString;

@interface _SBUIBiometricMatchingAssertion : _SBUIBiometricOperationAssertion <BSDescriptionProviding>
{
    unsigned long long _matchMode;
    long long _restartCount;
}

@property(nonatomic) long long restartCount; // @synthesize restartCount=_restartCount;
@property(readonly, nonatomic) unsigned long long matchMode; // @synthesize matchMode=_matchMode;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (id)initWithMatchMode:(unsigned long long)arg1 reason:(id)arg2 invalidationBlock:(CDUnknownBlockType)arg3;
- (id)initWithIdentifier:(id)arg1 forReason:(id)arg2 queue:(id)arg3 invalidationBlock:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

