//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <TSReading/TSWPAttachment.h>

@interface TSWPTextualAttachment : TSWPAttachment
{
}

- (id)stringEquivalentWithLayoutParent:(id)arg1;
- (void)setStringEquivalent:(id)arg1;
- (id)stringEquivalent;
- (id)stringWithPageNumber:(unsigned long long)arg1 pageCount:(unsigned long long)arg2 charIndex:(unsigned long long)arg3;
- (_Bool)shouldArchiveStringEquivalent;

@end

