//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreImage/CIDetector.h>

@class CIContext, FCRFaceDetector, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface CIFaceCoreDetector : CIDetector
{
    CIContext *context;
    NSMutableDictionary *featureOptions;
    _Bool _tracking;
    FCRFaceDetector *faceCoreDetector;
}

@property(retain) FCRFaceDetector *faceCoreDetector; // @synthesize faceCoreDetector;
@property(retain, nonatomic) CIContext *context; // @synthesize context;
- (id)featuresInImage:(id)arg1;
- (id)featuresInImage:(id)arg1 options:(id)arg2;
- (id)initWithContext:(id)arg1 options:(id)arg2;

@end

