//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, STUsageReportGraphDataPoint;

@interface STBarView : UIView
{
    _Bool _selected;
    STUsageReportGraphDataPoint *_dataPoint;
    NSArray *_sectionViews;
    NSArray *_sectionHeightConstraints;
}

@property(copy, nonatomic) NSArray *sectionHeightConstraints; // @synthesize sectionHeightConstraints=_sectionHeightConstraints;
@property(copy, nonatomic) NSArray *sectionViews; // @synthesize sectionViews=_sectionViews;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) STUsageReportGraphDataPoint *dataPoint; // @synthesize dataPoint=_dataPoint;
- (void).cxx_destruct;
- (void)setUpSectionHeightConstraints;
- (void)setUpSections;
- (id)initWithDataPoint:(id)arg1;

@end

