//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ScreenTimeUI/STRootGroupSpecifierProvider.h>

#import <ScreenTimeUI/AAUIDeviceToDeviceEncryptionHelperDelegate-Protocol.h>

@class NSString, PSSpecifier;

@interface STCloudSyncDataGroupSpecifierProvider : STRootGroupSpecifierProvider <AAUIDeviceToDeviceEncryptionHelperDelegate>
{
    _Bool _wantsToEnableSync;
    PSSpecifier *_toggleCloudSyncDataSpecifier;
}

@property(nonatomic) _Bool wantsToEnableSync; // @synthesize wantsToEnableSync=_wantsToEnableSync;
@property(retain, nonatomic) PSSpecifier *toggleCloudSyncDataSpecifier; // @synthesize toggleCloudSyncDataSpecifier=_toggleCloudSyncDataSpecifier;
- (void).cxx_destruct;
- (void)deviceToDeviceEncryptionHelper:(id)arg1 shouldContinueUpgradingUserToHSA2WithCompletion:(CDUnknownBlockType)arg2;
- (id)cloudSyncData:(id)arg1;
- (void)presentHSA2RepairUI:(CDUnknownBlockType)arg1;
- (void)performHSA2RepairIfNeeded:(CDUnknownBlockType)arg1;
- (void)setScreenTimeSyncing:(_Bool)arg1;
- (void)cancelChangeSync:(id)arg1;
- (void)acceptedPINToChangeSync:(id)arg1;
- (void)changeCloudSyncData:(_Bool)arg1;
- (void)setCloudSyncData:(id)arg1 specifier:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setCoordinator:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

