//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <MediaPlaybackCore/_MPCPlayerCommand.h>

#import "MPCPlayerChangeItemCommand.h"

@class NSString;

@interface _MPCPlayerChangeItemCommand : _MPCPlayerCommand <MPCPlayerChangeItemCommand>
{
    _Bool _supportsPreviousItem;
    _Bool _supportsPreviousSection;
    _Bool _supportsPreviousChapter;
    _Bool _supportsNextItem;
    _Bool _supportsNextSection;
    _Bool _supportsNextChapter;
    _Bool _supportsJumpToItem;
}

@property(nonatomic) _Bool supportsJumpToItem; // @synthesize supportsJumpToItem=_supportsJumpToItem;
@property(nonatomic) _Bool supportsNextChapter; // @synthesize supportsNextChapter=_supportsNextChapter;
@property(nonatomic) _Bool supportsNextSection; // @synthesize supportsNextSection=_supportsNextSection;
@property(nonatomic) _Bool supportsNextItem; // @synthesize supportsNextItem=_supportsNextItem;
@property(nonatomic) _Bool supportsPreviousChapter; // @synthesize supportsPreviousChapter=_supportsPreviousChapter;
@property(nonatomic) _Bool supportsPreviousSection; // @synthesize supportsPreviousSection=_supportsPreviousSection;
@property(nonatomic) _Bool supportsPreviousItem; // @synthesize supportsPreviousItem=_supportsPreviousItem;
- (id)changeToItem:(id)arg1;
- (id)changeToSection:(id)arg1;
- (id)nextChapter;
- (id)nextSection;
- (id)nextItem;
- (id)previousChapter;
- (id)previousSection;
- (id)previousItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

