//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError, PRDevice;

@protocol PRNearbyDeviceMonitorClientProtocol
- (void)didFailWithError:(NSError *)arg1;
- (void)didStopAggressiveScanning;
- (void)didStartAggressiveScanning;
- (void)didStopScanning;
- (void)didStartScanning;
- (void)didLoseDevice:(PRDevice *)arg1;
- (void)didUpdateDevice:(PRDevice *)arg1;
- (void)didFindDevice:(PRDevice *)arg1;
@end

