//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class TSCH3DScene, TSCH3DSceneObject;

@protocol TSCH3DSceneObjectDelegator
- (id)makeDelegateWithSceneObject:(TSCH3DSceneObject *)arg1 scene:(TSCH3DScene *)arg2;
- (id)makeDelegateWithScene:(TSCH3DScene *)arg1;
@end

