//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/TSDCanvasDelegate-Protocol.h>

@class TSDCanvas, TSDLayout;

@protocol TSDDynamicCanvasDelegate <TSDCanvasDelegate>
- (void)i_layoutUnregistered:(TSDLayout *)arg1;
- (void)i_layoutRegistered:(TSDLayout *)arg1;

@optional
- (void)i_canvasWillLayout:(TSDCanvas *)arg1;
@end

