//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, TSPFinalizeHandlerQueue;

__attribute__((visibility("hidden")))
@interface TSPReadCompletionInfo : NSObject
{
    NSMapTable *_objects;
    id <TSPReadCoordinator> _readCoordinator;
    TSPFinalizeHandlerQueue *_finalizeHandlerQueue;
}

@property(readonly, nonatomic) TSPFinalizeHandlerQueue *finalizeHandlerQueue; // @synthesize finalizeHandlerQueue=_finalizeHandlerQueue;
@property(readonly, nonatomic) id <TSPReadCoordinator> readCoordinator; // @synthesize readCoordinator=_readCoordinator;
@property(readonly, nonatomic) NSMapTable *objects; // @synthesize objects=_objects;
- (void).cxx_destruct;
- (id)initWithObjects:(id)arg1 readCoordinator:(id)arg2 finalizeHandlerQueue:(id)arg3;

@end

