//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <iWorkImport/TSPObject.h>

@class TSTColumnRowUIDMap, TSTInfo;

__attribute__((visibility("hidden")))
@interface TSTCategoryOrder : TSPObject
{
    TSTInfo *_tableInfo;
    TSTColumnRowUIDMap *_uidMap;
}

+ (UUIDData_5fbc143e)categoryColumnUID;
@property(retain) TSTColumnRowUIDMap *uidMap; // @synthesize uidMap=_uidMap;
@property(readonly) __weak TSTInfo *tableInfo; // @synthesize tableInfo=_tableInfo;
- (void).cxx_destruct;
- (id)columnRowUIDMap;
- (vector_4dc5f307)groupUidsGivenRowUids:(const vector_4dc5f307 *)arg1 selectedLevels:(const unordered_map_3e9d252a *)arg2;
- (void)removeRowUids:(const vector_4dc5f307 *)arg1;
- (void)insertRowUids:(const vector_4dc5f307 *)arg1 beforeUid:(const UUIDData_5fbc143e *)arg2;
- (void)saveToArchive:(struct CategoryOrderArchive *)arg1 archiver:(id)arg2;
- (void)saveToArchiver:(id)arg1;
- (void)loadFromArchive:(const struct CategoryOrderArchive *)arg1 unarchiver:(id)arg2;
- (void)loadFromUnarchiver:(id)arg1;
- (void)setRowOrder:(const vector_4dc5f307 *)arg1;
- (vector_4dc5f307)rowOrder;
- (_Bool)isValid;
- (id)sortedArrayFromArray:(id)arg1;
- (unsigned char)minimumCategoryLevelInRowRange:(struct _NSRange)arg1;
- (id)targetGroupFromRowIndex:(unsigned int)arg1 minSourceLevel:(unsigned char)arg2 templateRowUID:(UUIDData_5fbc143e *)arg3;
- (vector_4dc5f307)orderedRowUidsWithLabels;
- (vector_4dc5f307)orderedRowUidsFromUids:(const vector_4dc5f307 *)arg1;
- (id)copyWithContext:(id)arg1 tableInfo:(id)arg2;
- (id)initWithContext:(id)arg1;
- (id)initWithTableInfo:(id)arg1;
- (id)initWithTableInfo:(id)arg1 rowUids:(const vector_4dc5f307 *)arg2;
- (id)initWithContext:(id)arg1 tableInfo:(id)arg2 rowUids:(const vector_4dc5f307 *)arg3;

@end

