//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, NSTimer, UILabel;

__attribute__((visibility("hidden")))
@interface PUPhotoEditPerfHUD : UIView
{
    UILabel *_detailLabel;
    UILabel *_clockLabel;
    UILabel *_mainTimerLabel;
    UILabel *_resourceTimerLabel;
    UILabel *_resourceCheckingLabel;
    UILabel *_resourceDownloadingLabel;
    UILabel *_filterTimerLabel;
    UILabel *_autoCalcTimerLabel;
    UILabel *_saveTimerLabel;
    NSTimer *_timer;
    CDStruct_3139860e _mainTimerState;
    CDStruct_3139860e _resourceTimerState;
    CDStruct_3139860e _resourceCheckingState;
    CDStruct_3139860e _resourceDownloadingState;
    CDStruct_3139860e _filterTimerState;
    CDStruct_3139860e _autoCalcTimerState;
    CDStruct_3139860e _saveTimerState;
}

+ (void)_updateLabel:(id)arg1 withState:(CDStruct_3139860e)arg2 prefix:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) CDStruct_3139860e saveTimerState; // @synthesize saveTimerState=_saveTimerState;
@property(nonatomic) CDStruct_3139860e autoCalcTimerState; // @synthesize autoCalcTimerState=_autoCalcTimerState;
@property(nonatomic) CDStruct_3139860e filterTimerState; // @synthesize filterTimerState=_filterTimerState;
@property(nonatomic) CDStruct_3139860e resourceDownloadingState; // @synthesize resourceDownloadingState=_resourceDownloadingState;
@property(nonatomic) CDStruct_3139860e resourceCheckingState; // @synthesize resourceCheckingState=_resourceCheckingState;
@property(nonatomic) CDStruct_3139860e resourceTimerState; // @synthesize resourceTimerState=_resourceTimerState;
@property(nonatomic) CDStruct_3139860e mainTimerState; // @synthesize mainTimerState=_mainTimerState;
@property(retain, nonatomic) UILabel *saveTimerLabel; // @synthesize saveTimerLabel=_saveTimerLabel;
@property(retain, nonatomic) UILabel *autoCalcTimerLabel; // @synthesize autoCalcTimerLabel=_autoCalcTimerLabel;
@property(retain, nonatomic) UILabel *filterTimerLabel; // @synthesize filterTimerLabel=_filterTimerLabel;
@property(retain, nonatomic) UILabel *resourceDownloadingLabel; // @synthesize resourceDownloadingLabel=_resourceDownloadingLabel;
@property(retain, nonatomic) UILabel *resourceCheckingLabel; // @synthesize resourceCheckingLabel=_resourceCheckingLabel;
@property(retain, nonatomic) UILabel *resourceTimerLabel; // @synthesize resourceTimerLabel=_resourceTimerLabel;
@property(retain, nonatomic) UILabel *mainTimerLabel; // @synthesize mainTimerLabel=_mainTimerLabel;
@property(retain, nonatomic) UILabel *clockLabel; // @synthesize clockLabel=_clockLabel;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
- (void)_updateSaveTimerLabel;
- (void)_updateAutoCalcTimerLabel;
- (void)_updateFilterTimerLabel;
- (void)_updateResourceDownloadingLabel;
- (void)_updateResourceCheckingLabel;
- (void)_updateResourceTimerLabel;
- (void)_updateMainTimerLabel;
- (void)_timerTick;
- (_Bool)_needsTimer;
- (void)_updateTimer;
- (void)stopAndClearAllTimers;
- (void)stopSaveTimer;
- (void)startSaveTimer;
- (void)stopAutoCalcTimer;
- (void)startAutoCalcTimer;
- (void)stopFilterTimer;
- (void)startFilterTimer;
- (void)stopResourceDownloadingTimer;
- (void)startResourceDownloadingTimer;
- (void)stopResourceCheckingTimer;
- (void)startResourceCheckingTimer;
- (void)stopResourceLoadingTimer;
- (void)startResourceLoadingTimer;
- (void)stopMainTimer;
- (void)startMainTimerWithTime:(double)arg1;
- (void)startMainTimer;
@property(copy, nonatomic) NSString *detailText;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

