//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PhotosUI/PUFilteredMomentsViewController.h>

#import "PXChangeObserver.h"

@class NSString, UIViewController;

__attribute__((visibility("hidden")))
@interface PUPXFilteredMomentsViewController : PUFilteredMomentsViewController <PXChangeObserver>
{
    UIViewController *_containerViewController;
    id <PXGridPresentationNavigationItemDelegate> _navigationItemDelegate;
}

@property(nonatomic) __weak id <PXGridPresentationNavigationItemDelegate> navigationItemDelegate; // @synthesize navigationItemDelegate=_navigationItemDelegate;
@property(nonatomic) __weak UIViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
- (void).cxx_destruct;
- (void)observable:(id)arg1 didChange:(unsigned long long)arg2 context:(void *)arg3;
- (_Bool)isInPlaces:(id)arg1;
- (void)pu_performBarsVisibilityUpdatesWithAnimationSettings:(struct PUBarAnimationSettings)arg1;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateNavigationBarAnimated:(_Bool)arg1;
- (void)getEmptyPlaceholderViewTitle:(id *)arg1 message:(id *)arg2 buttonTitle:(id *)arg3 buttonAction:(CDUnknownBlockType *)arg4;
- (id)oneUpPresentationHelperViewController:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

