//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface PUSearchZeroKeywordSection : NSObject
{
    long long _sectionType;
    NSArray *_viewModels;
}

@property(readonly, nonatomic) NSArray *viewModels; // @synthesize viewModels=_viewModels;
@property(readonly, nonatomic) long long sectionType; // @synthesize sectionType=_sectionType;
- (void).cxx_destruct;
- (id)description;
- (void)removeItem:(id)arg1;
- (id)initWithType:(long long)arg1 viewModels:(id)arg2;

@end

