//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSpeechSynthesizer.h"

@interface NSSpeechSynthesizer (NSSpeechSynthesizerExtensions)
- (BOOL)setObject:(id)arg1 forProperty:(unsigned int)arg2 usingDataSize:(long long)arg3;
- (id)objectForProperty:(unsigned int)arg1 usingDataSize:(long long)arg2 withRequestedObjectClass:(Class)arg3;
- (void)setSpeechPitch:(float)arg1;
- (float)speechPitch;
- (void)setSpeechRate:(float)arg1;
- (float)speechRate;
@end

