//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WebVisiblePosition : NSObject
{
    struct WebObjectInternal *_internal;
}

+ (id)_wrapVisiblePositionIfValid:(struct VisiblePosition)arg1;
+ (id)_wrapVisiblePosition:(struct VisiblePosition)arg1;
@property(nonatomic) unsigned int affinity;
- (id)enclosingRangeWithCorrectionIndicator;
- (id)enclosingRangeWithDictationPhraseAlternatives:(id *)arg1;
- (_Bool)atAlphaNumericBoundaryInDirection:(int)arg1;
- (_Bool)requiresContextForWordBoundary;
- (_Bool)isEditable;
- (id)positionAtStartOrEndOfWord;
- (id)enclosingTextUnitOfGranularity:(int)arg1 inDirectionIfAtBoundary:(int)arg2;
- (_Bool)withinTextUnitOfGranularity:(int)arg1 inDirectionIfAtBoundary:(int)arg2;
- (id)positionOfNextBoundaryOfGranularity:(int)arg1 inDirection:(int)arg2;
- (_Bool)atBoundaryOfGranularity:(int)arg1 inDirection:(int)arg2;
- (id)positionByMovingInDirection:(int)arg1 amount:(unsigned long)arg2;
- (id)positionByMovingInDirection:(int)arg1 amount:(unsigned long)arg2 withAffinityDownstream:(_Bool)arg3;
- (_Bool)directionIsDownstream:(int)arg1;
- (unsigned char)textDirection;
- (id)description;
- (int)distanceFromPosition:(id)arg1;
- (int)compare:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)dealloc;
- (struct VisiblePosition)_visiblePosition;

@end

