//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ENSQLiteConnection, NSURL;

@interface ENExposureDatabase : NSObject
{
    NSURL *_databaseURL;
    ENSQLiteConnection *_connection;
}

+ (void)_obliterateDatabaseAtURL:(id)arg1 reason:(id)arg2 generateStackshot:(_Bool)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) ENSQLiteConnection *connection; // @synthesize connection=_connection;
- (void)purgeAllAndCloseWithReason:(id)arg1;
- (_Bool)purgeRecordsOlderThanDate:(id)arg1 error:(id *)arg2;
- (_Bool)setValue:(id)arg1 forKey:(id)arg2 type:(long long)arg3 expiryDate:(id)arg4 modDate:(id)arg5 connection:(id)arg6 error:(id *)arg7;
- (_Bool)setPropertyListValue:(id)arg1 forKey:(id)arg2 expiryDate:(id)arg3 error:(id *)arg4;
- (_Bool)setValue:(id)arg1 forKey:(id)arg2 expiryDate:(id)arg3 error:(id *)arg4;
- (_Bool)getValue:(id *)arg1 forKey:(id)arg2 ofClass:(Class)arg3 connection:(id)arg4 error:(id *)arg5;
- (_Bool)getValue:(id *)arg1 forKey:(id)arg2 ofClass:(Class)arg3 error:(id *)arg4;
- (_Bool)getAdvertisementCount:(long long *)arg1 error:(id *)arg2;
- (id)_advertisementWithRPIData:(id)arg1 encryptedAEMData:(id)arg2 timestamp:(long long)arg3 scanInterval:(int)arg4 typicalRSSI:(int)arg5 maxRSSI:(int)arg6 saturated:(int)arg7 counter:(int)arg8;
- (id)_advertisementsForTemporaryExposureKeyRowID:(long long)arg1 connection:(id)arg2 error:(id *)arg3;
- (id)advertisementCountsByTemporaryKeyDatasWithError:(id *)arg1;
- (_Bool)enumerateMatchedAdvertisementsWithError:(id *)arg1 handler:(CDUnknownBlockType)arg2;
- (_Bool)_insertPersistentTemporaryExposureKey:(id)arg1 connection:(id)arg2 error:(id *)arg3;
- (id)_persistentTemporaryExposureKeyWithKeyData:(id)arg1 regionIdentifier:(id)arg2 appBundleIdentifier:(id)arg3 rollingStartNumber:(long long)arg4 rollingPeriod:(long long)arg5 daysSinceOnsetOfSymptoms:(long long)arg6 diagnosisReportType:(long long)arg7 transmissionRiskLevel:(int)arg8;
- (_Bool)_updateExistingPersistentKeyIfNecessary:(id)arg1 replacementKey:(id)arg2 existingKeyID:(long long)arg3 connection:(id)arg4 error:(id *)arg5;
- (_Bool)_getExistingPersistentTemporaryExposureKey:(id *)arg1 rowID:(long long *)arg2 keyData:(id)arg3 connection:(id)arg4 error:(id *)arg5;
- (_Bool)_insertAdvertisement:(id)arg1 keyRowID:(long long)arg2 connection:(id)arg3 error:(id *)arg4;
- (_Bool)insertMatchedAdvertisements:(id)arg1 forKey:(id)arg2 error:(id *)arg3;
- (_Bool)_createSchemaWithConnection:(id)arg1 error:(id *)arg2;
- (_Bool)_createOrMigrateSchemaFromVersion:(long long)arg1 error:(id *)arg2;
- (_Bool)_reallyOpenDatabaseWithError:(id *)arg1;
- (void)close;
- (_Bool)openWithError:(id *)arg1;
@property(readonly, nonatomic) _Bool isOpen;
- (id)_initWithURL:(id)arg1;
- (id)initInMemoryDatabase;
- (id)initWithDirectoryURL:(id)arg1;
- (id)initWithURL:(id)arg1;

@end

