//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ARFLSpring : NSObject
{
    struct ARFLCompoundSpring _s;
    double _targetVelocity;
    double _previousTarget;
    _Bool _transitioningFromTracking;
    _Bool _tracking;
    double _minimumTarget;
    double _maximumTarget;
    double _rubberbandRange;
    double _rubberbandFactor;
    double _retargetResponseFraction;
    double _projectionDeceleration;
    struct ARFLSpringParameters _parameters;
    struct ARFLSpringParameters _trackingParameters;
}

+ (id)springWithValue:(double)arg1;
@property(nonatomic) double projectionDeceleration; // @synthesize projectionDeceleration=_projectionDeceleration;
@property(nonatomic) double retargetResponseFraction; // @synthesize retargetResponseFraction=_retargetResponseFraction;
@property(nonatomic) double rubberbandFactor; // @synthesize rubberbandFactor=_rubberbandFactor;
@property(nonatomic) double rubberbandRange; // @synthesize rubberbandRange=_rubberbandRange;
@property(nonatomic) double maximumTarget; // @synthesize maximumTarget=_maximumTarget;
@property(nonatomic) double minimumTarget; // @synthesize minimumTarget=_minimumTarget;
@property(nonatomic, getter=isTracking) _Bool tracking; // @synthesize tracking=_tracking;
@property(nonatomic) struct ARFLSpringParameters trackingParameters; // @synthesize trackingParameters=_trackingParameters;
@property(nonatomic) struct ARFLSpringParameters parameters; // @synthesize parameters=_parameters;
- (void)_updateForEffectiveParameters;
- (struct ARFLSpringParameters)_effectiveParameters;
- (void)step:(double)arg1;
- (void)setUsesDampingRatioResponseForSmoothing:(_Bool)arg1;
- (_Bool)usesDampingRatioResponseForSmoothing;
- (void)resetImmediatelyToValue:(double)arg1;
- (double)_projectedTargetForVelocity:(double)arg1;
@property(readonly, nonatomic) double projectedTarget; // @dynamic projectedTarget;
@property(nonatomic) double velocity; // @dynamic velocity;
@property(nonatomic) double target; // @dynamic target;
@property(nonatomic) double value; // @dynamic value;
- (id)init;
- (id)initWithValue:(double)arg1;

@end

