//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSObject<OS_dispatch_queue>;

@interface ARSessionMetrics : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    id <ARSessionMetricsReporting> _reporter;
    Class _configClass;
    NSDate *_startDate;
    NSDate *_frameStartDate;
    double _sessionTimeForLastBadFrameRecording;
    _Bool _initializingVIO;
    unsigned long long _frameCount;
    unsigned long long _badFrameCount;
    _Bool _positionInitialized;
    // Error parsing type: , name: _minPos
    // Error parsing type: , name: _maxPos
    _Bool _hasInitialWorldMap;
    _Bool _relocalizingToInitialWorldMap;
}

- (void).cxx_destruct;
- (void)_recordBadFramePercentageWithBucket:(id)arg1;
- (void)_recordBadFramePercentageFinal:(_Bool)arg1;
- (id)_baseKey;
- (id)arkitBasedKey:(id)arg1;
- (id)configBasedKey:(id)arg1;
- (void)_recordSessionEnd;
- (void)sessionStopped;
- (void)saveMapWithFrame:(id)arg1;
- (void)sessionDidUpdateFrame:(id)arg1;
- (void)sessionStartedWithConfiguration:(id)arg1;
- (id)queue;
- (id)initWithReporter:(id)arg1;
- (id)init;

@end

