//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSUUID.h"

@interface NSUUID (ARAdditions)
+ (id)ar_UUIDWithIntegerValue:(unsigned long long)arg1;
+ (id)ar_zeroUUID;
- (unsigned long long)ar_integerValue;
@end

