//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFBulletin;

@interface SASBulletinCacheNode : NSObject
{
    AFBulletin *_bulletin;
    SASBulletinCacheNode *_previousNode;
    SASBulletinCacheNode *_nextNode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SASBulletinCacheNode *nextNode; // @synthesize nextNode=_nextNode;
@property(retain, nonatomic) SASBulletinCacheNode *previousNode; // @synthesize previousNode=_previousNode;
@property(retain, nonatomic) AFBulletin *bulletin; // @synthesize bulletin=_bulletin;

@end

