//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIFoundation/NSTextAttachment.h>

#import <UIKitCore/UIAccessibilityContentSizeCategoryImageAdjusting-Protocol.h>

@class NSString;

@interface NSTextAttachment (UIAccessibilityContentSizeCategoryImageAdjusting) <UIAccessibilityContentSizeCategoryImageAdjusting>
+ (id)textAttachmentWithImage:(id)arg1;
+ (id)_imageFromAttachment:(id)arg1;
+ (_Bool)_attachmentHasImage:(id)arg1;
@property(nonatomic) _Bool adjustsImageSizeForAccessibilityContentSizeCategory;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

