//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC12FMNetworking27FMNAuthenticationCredential : _TtCs12_SwiftObject
{
    // Error parsing type: , name: authToken
    // Error parsing type: , name: personId
    // Error parsing type: , name: hostName
    // Error parsing type: , name: accountType
}

@end

