//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ChatKit/NSObject-Protocol.h>

@class IMBalloonPlugin, IMBalloonPluginDataSource, NSDate;
@protocol CKFullScreenAppViewControllerProtocol;

@protocol CKFullScreenAppViewControllerDelegate <NSObject>

@optional
- (BOOL)shouldAlwaysShowAppTitle;
- (BOOL)fullscreenAppViewControllerShouldDismissOnDragSuccess:(id <CKFullScreenAppViewControllerProtocol>)arg1;
- (double)fullscreenAppViewControllerCollapsedHeaderHeight:(id <CKFullScreenAppViewControllerProtocol>)arg1;
- (double)fullscreenAppViewControllerCollapsedContentHeight:(id <CKFullScreenAppViewControllerProtocol>)arg1;
- (void)fullscreenAppViewControllerDidTransitionFromOrientation:(long long)arg1 toOrientation:(long long)arg2;
- (void)fullscreenAppViewControllerSwitcherDidSelectAppManager:(id <CKFullScreenAppViewControllerProtocol>)arg1;
- (void)fullscreenAppViewControllerSwitcherDidSelectAppStore:(id <CKFullScreenAppViewControllerProtocol>)arg1;
- (void)fullscreenAppViewController:(id <CKFullScreenAppViewControllerProtocol>)arg1 hasUpdatedLastTouchDate:(NSDate *)arg2;
- (void)fullscreenAppViewController:(id <CKFullScreenAppViewControllerProtocol>)arg1 wantsToSwitchToPlugin:(IMBalloonPlugin *)arg2 datasource:(IMBalloonPluginDataSource *)arg3;
- (void)fullscreenAppViewControllerWantsToCollapse:(id <CKFullScreenAppViewControllerProtocol>)arg1;
@end

