//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSWindowDelegate.h"

@class NSString, NSWindow;

@interface _NSMagnifier : NSObject <NSWindowDelegate>
{
    NSWindow *_magnifyingGlassWindow;
    BOOL _continuous;
}

+ (id)sharedMagnifier;
@property BOOL continuous; // @synthesize continuous=_continuous;
- (void)trackMagnifierWithDelegate:(id)arg1;
- (void)_createMagnifyingGlassWindow;
- (Class)magnifyingGlassContentViewClass;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

