//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface FKAddressBook : NSObject
{
    void *_addressBook;
    NSObject<OS_dispatch_queue> *_operationQueue;
}

+ (void)performBlock:(CDUnknownBlockType)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(nonatomic) void *addressBook; // @synthesize addressBook=_addressBook;
- (void)dealloc;
- (id)init;

@end

