//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FLReachabilityObserver : NSObject
{
    CDUnknownBlockType _completionHandler;
}

+ (_Bool)isNetworkReachable;
+ (_Bool)isAirplaneModeActiveWithoutWifi;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void)dealloc;
- (void)_reachabilityChanged:(id)arg1;
- (void)disableAirplaneModeAndWaitForNetworkWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

