//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ICRandomTextGenerator, NSMutableDictionary;

@interface ICObfuscator : NSObject
{
    ICRandomTextGenerator *_randomTextGenerator;
    NSMutableDictionary *_imageMap;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *imageMap; // @synthesize imageMap=_imageMap;
@property(retain, nonatomic) ICRandomTextGenerator *randomTextGenerator; // @synthesize randomTextGenerator=_randomTextGenerator;
- (id)obfuscatedImageOfSize:(struct CGSize)arg1;
- (id)obfuscatedStringOfLength:(unsigned long long)arg1;
- (id)obfuscateString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

