//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CPMLDB, CPMLSchema, CPMLStorageManager, NSDictionary;

@interface CPMLTrainer : NSObject
{
    _Bool shouldFail;
    struct sqlite3 *modelDB;
    NSDictionary *modelPlist;
    CPMLDB *cpmlDB;
    struct CPMLCDB *cpCDB;
    struct CPMLAlgorithm *cpMLAlgo;
    struct CPMLRemapper *cpRemapper;
    CPMLSchema *cpmlSchema;
    struct CPMLStatistics *trainerCPStatistics;
    struct CPMLSerialization *trainerCPSerializer;
    struct CPMLTunableData *cpTuneableData;
    int mapFunction;
    struct CPMLDelegate *_cpmlDelegate;
    CPMLStorageManager *_storageManager;
    id <CPMLAlgorithmProtocol> _theDelegate;
}

- (void).cxx_destruct;
- (void)buildTrainingMachineLearningAlgorithm:(id)arg1;
- (void)train:(_Bool)arg1;
- (id)fileProtectionClassRequest:(id)arg1;
- (void)dealloc;
- (id)init:(id)arg1 withModelDBPath:(id)arg2 withPropertyList:(id)arg3;
- (id)getSolution;

@end

