//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PepperUICore/PUICTableViewCell.h>

@class UILabel;

@interface PUICQuickboardListContentUnavailableCell : PUICTableViewCell
{
    UILabel *_titleLabel;
    UILabel *_messageLabel;
}

- (void).cxx_destruct;
- (void)_handleContentSizeCategoryDidChange:(id)arg1;
- (id)_preferredFont;
- (void)_initializeFonts;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)configureWithTitle:(id)arg1 message:(id)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

