//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SOSUtilities : NSObject
{
}

+ (void)setAllowedToMessageSOSContacts:(_Bool)arg1;
+ (_Bool)isAllowedToMessageSOSContacts;
+ (void)setPlayAudioDuringCountdown:(_Bool)arg1;
+ (_Bool)shouldPlayAudioDuringCountdown;
+ (void)setAutomaticCallCountdownEnabled:(_Bool)arg1;
+ (_Bool)isAutomaticCallCountdownEnabled;
+ (long long)SOSSelectableTriggerMechanismCapability;
+ (_Bool)deviceHasHomeButton;
+ (_Bool)isD2xDevice;
+ (long long)defaultSOSTriggerMechanism;
+ (long long)SOSTriggerMechanismForClickCount:(long long)arg1;
+ (long long)currentSOSTriggerMechanism;
+ (long long)SOSTriggerClickCount;
+ (_Bool)canTriggerSOSWithClicks;
+ (_Bool)canTriggerSOSWithVolumeLockHold;
+ (_Bool)mustAllowThreeClickTrigger;
+ (void)setLongPressTriggersEmergencySOS:(_Bool)arg1;
+ (_Bool)longPressTriggersEmergencySOS;
+ (id)_userFriendsDefaults;
+ (id)_userSOSDefaults;

@end

