//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton;

@interface AMGetItemsPanelController : NSWindowController
{
    NSButton *_cancelButton;
    NSButton *_addButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSButton *_addButton; // @synthesize _addButton;
@property(nonatomic) __weak NSButton *_cancelButton; // @synthesize _cancelButton;
- (void)cancelAction:(id)arg1;
- (void)addAction:(id)arg1;

@end

