//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CalendarDaemon/CADAlarmEngineInterface-Protocol.h>
#import <CalendarDaemon/CADCalendarInterface-Protocol.h>
#import <CalendarDaemon/CADCalendarItemInterface-Protocol.h>
#import <CalendarDaemon/CADCalendarToolInterface-Protocol.h>
#import <CalendarDaemon/CADDatabaseInterface-Protocol.h>
#import <CalendarDaemon/CADEventInterface-Protocol.h>
#import <CalendarDaemon/CADInternalInterface-Protocol.h>
#import <CalendarDaemon/CADMigrationInterface-Protocol.h>
#import <CalendarDaemon/CADNotificationMonitorInterface-Protocol.h>
#import <CalendarDaemon/CADObjectInterface-Protocol.h>
#import <CalendarDaemon/CADReminderInterface-Protocol.h>
#import <CalendarDaemon/CADSourceInterface-Protocol.h>
#import <CalendarDaemon/CADSpotlightInterface-Protocol.h>
#import <CalendarDaemon/CADSyncInterface-Protocol.h>
#import <CalendarDaemon/CADTestingInterface-Protocol.h>

@protocol CADInterface <CADDatabaseInterface, CADObjectInterface, CADSourceInterface, CADCalendarInterface, CADCalendarItemInterface, CADEventInterface, CADReminderInterface, CADAlarmEngineInterface, CADNotificationMonitorInterface, CADSpotlightInterface, CADInternalInterface, CADTestingInterface, CADMigrationInterface, CADSyncInterface, CADCalendarToolInterface>
@end

