//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CRFeedbackListener.h"

@class CRKCardSectionViewController, INIntent, INInteraction, NSSet, UIViewController;

@protocol CRKCardSectionViewControllerDelegate <CRFeedbackListener>

@optional
- (long long)preferredPunchoutIndexForCardSectionViewController:(CRKCardSectionViewController *)arg1;
- (void)cardSectionViewController:(CRKCardSectionViewController *)arg1 didSelectPreferredPunchoutIndex:(long long)arg2;
- (void)presentViewController:(UIViewController *)arg1 forCardSectionViewController:(CRKCardSectionViewController *)arg2;
- (void)cardSectionViewController:(CRKCardSectionViewController *)arg1 didHandleParameters:(NSSet *)arg2 forInteraction:(INInteraction *)arg3;
- (struct CGSize)boundingSizeForCardSectionViewController:(CRKCardSectionViewController *)arg1;
- (void)cardSectionViewController:(CRKCardSectionViewController *)arg1 requestsHandlingOfIntent:(INIntent *)arg2;
- (void)cardSectionViewControllerBoundsDidChange:(CRKCardSectionViewController *)arg1;
- (void)cardSectionViewControllerDidFinishLoading:(CRKCardSectionViewController *)arg1;
- (_Bool)performCommand:(id <CRCommand>)arg1 forCardSectionViewController:(CRKCardSectionViewController *)arg2;
- (_Bool)canPerformCommand:(id <CRCommand>)arg1 forCardSectionViewController:(CRKCardSectionViewController *)arg2;
@end

