//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/NSObject-Protocol.h>

@class NSString, _SFDialogView;

@protocol _SFDialogViewDelegate <NSObject>
- (void)dialogView:(_SFDialogView *)arg1 didSelectActionAtIndex:(unsigned int)arg2 withInputText:(NSString *)arg3 passwordText:(NSString *)arg4;
@end

