//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

#import <SafariServices/SFPasswordRemoteViewControllerProtocol-Protocol.h>

@class NSString;
@protocol SFPasswordRemoteViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SFPasswordRemoteViewController : _UIRemoteViewController <SFPasswordRemoteViewControllerProtocol>
{
    id <SFPasswordRemoteViewControllerDelegate> _delegate;
}

+ (id)exportedInterface;
+ (id)passwordServiceViewControllerName;
+ (id)requestViewControllerWithConnectionHandler:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak id <SFPasswordRemoteViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)willDismissServiceViewController;
- (void)viewServiceDidTerminateWithError:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

